### ISSUE TITLE
DSpot for dummies using the command line

### ISSUE THREAD

**Issue by CaelInria** [STAMP-project/dspot#134]
A very step by step tutorial on how to run DSpot on your project using the command line.

**Comment by danglotb** [comment]
Hello @CaelInria , 

Could you look at #135 , and tell me if new informations are enough to understand how to run DSpot.

Thank you.

**Comment by danzone** [comment]
Hello @CaelInria , @danglotb, I will perform and document a step-by-step on Windows and Linux machines on DSpot and Descartes, in order to have the tutorial sessions we mentioned yesterday afternoon. This will be the first step, in the next few days I will give feedbacks

**Comment by danzone** [comment]
Task completed by september Padua meeting
