### ISSUE TITLE
Descartes Gradle plugin - Issue while executing pitest with Descartes mutation engine

### ISSUE THREAD

**Issue by danzone** [STAMP-project/dspot#142]
Hello, I'm facing this issue with Gradle java projects: if I run the task `gradle pitest`, having configured descartes plugin as described in https://github.com/STAMP-project/pitest-descartes, I got an error. It seems a classpath problem: descartes plugin seems to require pitest 1.2.x library, while gradle pitest plugin requires pitest 1.x library.
Attached a zip file with the test project and the gradle build file: this afternoon I got a classnotfound error on class org.pitest.util.InputstreamLineIterable (it belongs to pitest 1.x... library): pitest 1.2.x actually doesn't have this class, but in fact now I'm facing a different error (a match input error).
What's wrong with my Descartes plugin usage?
[gradle-test-projects-descartes.tar.gz](https://github.com/STAMP-project/dspot/files/1166175/gradle-test-projects-descartes.tar.gz)

**Comment by danglotb** [comment]
Hi @danzone 

First, in your build.gradle, you specify the 0.2-SNAPSHOT version of descartes while on [stamp maven repos](https://github.com/STAMP-project/stamp-maven-repository) only the 0.1-SNAPSHOT is deployed.

Second, you use `mutators = ['ALL']` while in descartes there is no such mutators.

On my side, I changed:

`pitest 'fr.inria.stamp:descartes:0.2-SNAPSHOT' ` by `pitest 'fr.inria.stamp:descartes:0.1-SNAPSHOT'

and 

`mutators = ['ALL']` by `mutators = ['\'a\'']` because the example is an usage of charAt, which return a char. See that we have to escape the simple quote, to specify that it is a char (the Java primitive type).

I ran the command: `gradle pitest` and obtain:
```
10:41:21 AM PIT >> INFO : Sending 1 test classes to minion
10:41:21 AM PIT >> INFO : Sent tests to minion
10:41:22 AM PIT >> INFO : MINION : 10:41:22 AM PIT >> INFO : Checking environment

10:41:22 AM PIT >> INFO : MINION : 10:41:22 AM PIT >> INFO : Found  6 tests

10:41:22 AM PIT >> INFO : MINION : 10:41:22 AM PIT >> INFO : Dependency analysis reduced number of potential tests by 0

10:41:22 AM PIT >> INFO : MINION : 10:41:22 AM PIT >> INFO : 6 tests received

-10:41:22 AM PIT >> INFO : Calculated coverage in 0 seconds.
10:41:22 AM PIT >> INFO : Created  1 mutation test units
/=10:41:23 AM PIT >> INFO : Completed in 1 seconds
================================================================================
- Timings
================================================================================
> scan classpath : < 1 second
> coverage and dependency analysis : < 1 second
> build mutation tests : < 1 second
> run mutation analysis : < 1 second
--------------------------------------------------------------------------------
> Total  : 1 seconds
--------------------------------------------------------------------------------
================================================================================
- Statistics
================================================================================
>> Generated 1 mutations Killed 1 (100%)
>> Ran 1 tests (1 tests per mutation)
================================================================================
- Mutators
================================================================================
> 'a'
>> Generated 1 Killed 1 (100%)
> KILLED 1 SURVIVED 0 TIMED_OUT 0 NON_VIABLE 0 
> MEMORY_ERROR 0 NOT_STARTED 0 STARTED 0 RUN_ERROR 0 
> NO_COVERAGE 0 
--------------------------------------------------------------------------------

BUILD SUCCESSFUL

Total time: 2.944 secs
```

I don't know if we need the snapshot 0.2 of descartes for now. I think we can use the 0.1.

Thank you!

Hope It can help you :-)

Best.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin,
Please, close this issue, since DSpot is not using Descartes anymore, and I've been able to run Descartes in DHell project. I will try with my own and report to you the results.
Yosu

**Comment by monperrus** [comment]
Yosu, I propose that you have write access to the repo so that you can also manage issues.

@all WDYT?

**Comment by jesus-gorronogoitia** [comment]
Bonjour Martin, thanks for this offering

**Comment by danzone** [comment]
Completely agree!
