### ISSUE TITLE
DSpot: exception thrown running DSpot in Atos UC: Supersede IF module

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#161]
**Issue Type**: possible bug/wrong configuration/wrong use
**Description**: DSpot executed on customed Atos UC Supersede IF component raises a ClassNotFoundException when amplifying a concrete test, after being amplifying successfully many other previous tests. Class not found in included in dependency, declared in pom.xml. Executing Atos UC test with mvn test does not show any exception. Apparently, classpath is not detected correctly, could be?

BTW, Readme.md documentation shows an error when describing the usage of DSpot for tailored proyect. Instead of `java -cp target/dspot-*-jar-with-dependencies.jar fr.inria.stamp.Main path/To/my.properties` in `Running on your own project` section, it should be `java -cp target/dspot-*-jar-with-dependencies.jar fr.inria.stamp.Main -p path/To/my.properties`

_Questions_? 

1. Since DSpot seems to work without exception for many Atos tests, failing in one, could it be possible to configure it to skip (exclude) some tests so they are not amplified? In documentation I see we can select concrete test cases to be amplified.
2. When declaring test to be amplified, could be possible to use Ant-like (or regular expressions) to represent a set of related tests to be amplified, avoiding to list them all?

**Reproducibility**: always
**Severity**: minor
**Tool**: DSpot GitHub repository, version 28/08/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**:
DSpot packaged and tested successfully following readme.md, after clonning the repository the https://github.com/STAMP-project/dspot.git repository
See https://github.com/STAMP-project/pitest-descartes/issues/17 for cloning and accessing the Supersede IF from GitHub repository. Then, instead of building it using Gradle, use Maven: `mvn package` 
DSpot was executed from DSpot directory, issuing the command: `java -cp target/dspot-1.0.0-jar-with-dependencies.jar fr.inria.stamp.Main -p ./src/test/resources/test-projects/test-projects-supersede-if.properties`
**Files**:
I attach the full log of executing DSpot on Atos Supersede IF component:
[DSpot_execution_supersede_if.txt](https://github.com/STAMP-project/dspot/files/1256901/DSpot_execution_supersede_if.txt)
Also, the test-projects-supersede-if.properties: 

_#relative path to the project root from dspot project
project=../../../Supersede/Git/integration/IF/API/eu.supersede.if.api
#relative path to the source project from the project properties
src=src/main/java/
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
#filter used to amplify specific test cases
filter=example.*
#path to the output folder
outputDirectory=build/trash/_

And the Maven dependency tree for Supersede IF:
[Supersede_IF_Maven_Dependency_Tree.txt](https://github.com/STAMP-project/dspot/files/1256903/Supersede_IF_Maven_Dependency_Tree.txt), showing the resolution of the dependency, andes-client, which contains the class not found.

**Relationships**: None
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

Thanks for using DSpot.

I think your problem come from the fact that the documentation is unclear. In your properties file, you let: `filter=example.*`. The fact is, that dspot will feed the command of pit with this as targeted classes. I  think in your project there is no such package named `example`. 

That is why, in the trace, pit test inform us that it does find any test or target classes:
```
2:55:34 PM PIT >> INFO : Sending 0 test classes to minion
2:55:34 PM PIT >> INFO : Sent tests to minion
2:55:34 PM PIT >> INFO : Calculated coverage in 0 seconds.
2:55:34 PM PIT >> INFO : Created  0 mutation test units
```

I suggest to change the value of the property filter to a matching package / classes (it is source package/class not test class)

I'll propose a pull request to clarify the usage of this property.

> Since DSpot seems to work without exception for many Atos tests, failing in one, could it be possible to configure it to skip (exclude) some tests so they are not amplified? In documentation I see we can select concrete test cases to be amplified.

No, it is not yet possible. However, it would be a great feature. Thanks for the suggestion.

> When declaring test to be amplified, could be possible to use Ant-like (or regular expressions) to represent a set of related tests to be amplified, avoiding to list them all?

Yes, it can be added to DSpot. We could filter using a given regular expression, on all test classes of the spoon model in DSpot. 

Thank for your suggestions, I'll work on propose some changes as soon as possible.

Best,

Benjamin.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin.
Thanks for suggestions. So, filter describes the qualified package names of Test classes to be included in the amplification process, doesn't it?. I though it described the package name for generated amplified test. Indeed, in the CMD interface documentation, it describes the usage of:
`[(-t|--test) my.package.MyClassTest1:my.package.MyClassTest2:...:my.package.MyClassTestN ]
            [optional] fully qualified names of test classes to be amplified. If the
            value is all, DSpot will amplify the whole test suite. (default: all)` to specify the test classes to be included. I did so, selecting only one class, but not mutations where created. Please, clarify in documentation. One example would be helpful. 

I will test it again and let you know. 

Regarding regular expressions, could you please add this support in documentation, as well as an example?

**Comment by jesus-gorronogoitia** [comment]
BTW, in this issue I reported a possible classpath issue. Once I fix the properties configuration with correct qualified package names, I will run DSpot for all target project test suites, checking whether the classpath issue has gone or not and report back to you.

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

>So, filter describes the qualified package names of Test classes to be included in the amplification process, doesn't it?

No, the filter is describing which source classes you want to target. In other hand, often we use the same hierarchy in the source code and the test suite.

The documentation is wrong, I have to fix as soon as possible. The fact is, that the property is used for two different usage, and this is very confusing. I'll split up both usages into two new options/property.

> Indeed, in the CMD interface documentation, it describes the usage of:
[(-t|--test) my.package.MyClassTest1:my.package.MyClassTest2:...:my.package.MyClassTestN ] [optional] fully qualified names of test classes to be amplified. If the value is all, DSpot will amplify the whole test suite. (default: all)

This options allows you to amplify specific test classes by giving their full qualified name. It is different from the property filter.

Thank you,

**Comment by jesus-gorronogoitia** [comment]
I've not sure of getting the point, but I've tried this:
In this screenshot 
![supersedeif_package_hierarchy](https://user-images.githubusercontent.com/3658315/29814514-eb6bdc62-8cad-11e7-8f61-80aba8132d65.png)
 you can see the hierarchy of Supersede IF test suites. The common package name is eu.supersede.integration.api, so in the dspot properties file, I've used this filter
`filter=eu.supersede.integration.api.*`
Then, I've launched DSpot with this command line:
`java -cp target/dspot-1.0.0-jar-with-dependencies.jar fr.inria.stamp.Main -p ./src/test/resources/test-projes/test-projects-supersede-if.properties -t eu.supersede.integration.api.security.test.IFAuthenticationManagerTest` so only the IFAuthenticationManagerTest is amplified.
DSpot starts working, but it gets blocked after seconds, only showing this input:
_00:00 DEBUG: Selected Maven automatic builder.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building eu.supersede.if.api 0.3.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.um.ws.api.stub:jar:4.2.2 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.tenant.mgt.stub:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.um.ws.api:jar:4.2.2 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.user.api:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.user.core:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.utils:jar:4.2.0 is missing, no dependency information available
[WARNING] The POM for opensaml.wso2:opensaml2:jar:2.4.1.wso2v1 is missing, no dependency information available
[WARNING] The POM for org.wso2.andes.wso2:andes-client:jar:3.1.1 is missing, no dependency information available
[WARNING] The POM for org.apache.geronimo.specs.wso2:geronimo-jms_1.1_spec:jar:1.1.0.wso2v1 is missing, no dependency information available
[WARNING] The POM for org.wso2.carbon:org.wso2.carbon.logging:jar:4.4.1 is missing, no dependency information available
[WARNING] The POM for org.wso2.securevault:org.wso2.securevault:jar:1.0.0-wso2v2 is missing, no dependency information available
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:build-classpath (default-cli) @ eu.supersede.if.api ---
[INFO] Wrote classpath file '/home/yosu/Projects/STAMP/Git/dspot/tmpDir/tmp/cp'.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.653 s
[INFO] Finished at: 2017-08-29T11:21:14+02:00
[INFO] Final Memory: 17M/225M
[INFO] ------------------------------------------------------------------------_

**Comment by danglotb** [comment]
It seems the configuration is ok.

The last step we have in the trace is the building of the classpath (in the file named cp). The next step is to compile sources, test sources and the building of the spoon model. It might take some time to do.

I have question: Is it a multi-module project? 

If it is the case, the property project should point to the directory of the top module (folder where the top-parent pom file is) and point the property targetModule to the given module (relative from the property project).

I suggest you to have a look to [the properties file](https://github.com/STAMP-project/dspot/blob/master/src/test/resources/multiple-pom/deep-pom-modules.properties) of the resources used in test cases of DSpot.

```
#the root project: where the first parent pom is present
project=src/test/resources/multiple-pom
#relative path to the targeted module: used as follow <project + / + targetModule>
targetModule=module-1/module-2-1/
```

**Comment by jesus-gorronogoitia** [comment]
No, it is not a multi-module project.  Maven compilation, test execution and package takes 19 sec, when executed in CLI standalone, without DSpot.
However, when launching DSpot, execution traces stop after the point shown in logs above. I will try it again, keeping it working. Last time, I kept if for minutes. I could break the process with CRTL-C, so Java process was not hang. Is it any way to trace the execution or increase the logs? something like verbose execution?

**Comment by danglotb** [comment]
> Is it any way to trace the execution or increase the logs? something like verbose execution?

I just merged changes that allow you to activate log in Spoon, by adding `--verbose ` to the command line.

**Comment by jesus-gorronogoitia** [comment]
Before testing with verbose gives the following output: 
[DSpot_execution_supersede_if_single_test_verbose.txt](https://github.com/STAMP-project/dspot/files/1262557/DSpot_execution_supersede_if_single_test_verbose.txt) 
DSpot stops showing logs, although not quitting the execution, but it reduces the CPU consumption drastically.

I tried to restrict the amplification using the properties filter, replacing
`filter=eu.supersede.integration.api.*` by `filter=eu.supersede.integration.api.security.test.*`
In this case, DSpot continuous working until it stops reporting a problem and throwing an execption, shown in this file 
[DSpot_execution_supersede_if_single_test_more_restrictive.txt](https://github.com/STAMP-project/dspot/files/1262563/DSpot_execution_supersede_if_single_test_more_restrictive.txt)

**Comment by danglotb** [comment]
In the former case, DSpot is running PIT using the whole test suite. The results of this analysis will be use as a baseline to amplify test (we will keep only amplified test that kill mutant that the existing test do not kill). That is why it seems to be stuck, but actually it is running maven. I'll add a trace to see which maven goals DSpot is using.

In the latter case, pit is failing because some of test fails (we can see that it is the same step than above, but with less class, the output is printed). 

For a quick "fix", and try to use DSpot, I suggest you first to add to your property file the following line:
`excludedClasses=eu.supersede.integration.api.security.test.IFAuthenticationManagerTest,eu.supersede.integration.api.security.test.IdentityManagerClientTest`

This line will exclude failing test classes in the pit execution, and pit might be pass.

To understand why the execution of those test classes fail in pit (I guess they pass when we execute them with maven), we can have look to the [website](http://pitest.org/faq/) of pit:

> My tests normally run green but PIT says the suite isn’t green
> Most comonly this is because either :
> - PIT is picking up tests that are not included/are excluded in the normal test config
> - Some test rely on an environment variable or other property set in the test config, but not set in the pitest config 
> - The tests have a hidden order dependency that is not revealed during the normal test run

> If you are using an unusual or custom JUnit runner this can also sometimes causes problems. To make things fast PIT does some tricksy stuff to split your tests into small independent units. This works well with most JUnit runners but if you encounter one where it doesn’t please post to the user group.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin, sorry I was busy with an STAMP deliverable, so I moved my attention to another point. Are you attending next GA in Padova? If so, we can discuss there above issue about how to use DSpot in Atos scenario. I will investigate this issue in more detail in next days. The text suite configured to be included in DSpot has a test tagged as @Ignore because it causes problems. Maybe this JUnit @ignore tag is not considered by PIT and this is the reason the suite has a failing test.

**Comment by danglotb** [comment]
Hello

> Are you attending next GA in Padova? If so, we can discuss there above issue about how to use DSpot in Atos scenario. 

Sure I am, we will discuss about it! :)

> The text suite configured to be included in DSpot has a test tagged as @ignore because it causes problems. Maybe this JUnit @ignore tag is not considered by PIT and this is the reason the suite has a failing test.

Maybe it is, I don't remember if pit support the ignore tag.

Thank you
