### ISSUE TITLE
Test error related to Maven

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/dspot#172]
Tests fail when trying to build dspot. Errors: 54, which all seems to have the same reason:
Maven executable not found at: C:\Dev\apache-maven-3.3.9\bin\mvn.bat
There is no file "mvn.bat" in my maven installation. I also checked the latest version of maven.
This is on Windows 10.

**Comment by danglotb** [comment]
Hello @ltboye 

> C:\Dev\apache-maven-3.3.9\
Is it the path to your maven installation?

Did you set properly the environment variable `$MAVEN_HOME`?

In this condition, it will be hard to find the problem, I am sorry.

Cheers.

**Comment by ltboye** [comment]
Yes, its set and it appears to be correct, because the maven path in the error messages is correct. It's just that there is no such file "mvn.bat" in maven.

**Comment by danglotb** [comment]
Hello,

I just merged  #174. 

DSpot uses now the implementation by apache of maven invoker.

However, on my window, I have a `mvn.bat`, which the executable of maven I guess, in the maven installation folder.

Thank.
