### ISSUE TITLE
feature: add support for DSpot in the continuous integration server CI

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#191]
Specification is : https://github.com/STAMP-project/dspot/wiki/Specification-of-DSpot-microservice-in-CI 

This is meant to be updated by all of us.

**Comment by monperrus** [comment]
depends on #174

**Comment by monperrus** [comment]
@danzone @luandrea @nicolabertazzo 

what do you think of https://github.com/STAMP-project/dspot/wiki/Specification-of-DSpot-microservice-in-CI?

**Comment by danzone** [comment]
Hi @monperrus , I will discuss it with @luandrea and @nicolabertazzo during this week. We will contribute the wiki page with additional info.

**Comment by monperrus** [comment]
Excellent! Looking forward to it!

**Comment by danglotb** [comment]
Closing this issue. 

We have two majors lead to this: 

1. @spookyvale works on a Jenkins plugin for DSpot. 

2. I worked on the diff-test-selection plugin. In addition to the maven plugin of DSpot, one should be able to run **DSpot** in the CI.
