### ISSUE TITLE
feature: improve input modification with the cartesian product of all Data Input Modification.

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#203]
I was thinking on an improvement of the input modification.

I propose to split the input modification into two categories:

1. Structural Input Modification: This step will generate new method call on existing object, *i.e.* the object under step. It will also generate new objects to give them as parameters of the newly called method.
2. Data Input Modification: This step will modify all literals used in the tests, one by one.

We should apply multiple Data Input Modification for a single Structural Input Modification. That is to say, we should apply the cartesian product of all Data Input Modification.

If the budget is not finish (time or number of iteration), we apply a new Structural Input Modification, and do the process again.

In this way, the input modification will be still an amplification, and yet exhaustive.

This is not a requested feature for now, just to open the discussion.

**Comment by monperrus** [comment]
In general, I think it's a very good idea to aim at an exhaustive exploration of the amplification
space.

This requires to carefully define the search space so that it becomes tractable.

It would be scientifically founded on the small scope hypothesis which is also behind Alloy.

**Comment by monperrus** [comment]
See paper "Evaluating the Small Scope Hypothesis" paper

**Comment by monperrus** [comment]
See also "Finding bugs with a constraint solver"

**Comment by danglotb** [comment]
The Ex2Amplifier aims to do that. However, we could not find any symbolic engine able to run on modern software.
