### ISSUE TITLE
in I-amplification also remove assertion from alternative assertion frameworks (Harmcrest/Google Truth/Assert4j)

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#213]
and not only Junit assertions

**Comment by monperrus** [comment]
See also #114

**Comment by danglotb** [comment]
See #307 

**DSpot** removes now assert from **JUnit**, **Hamcrest** and **Google Truth**.

**Comment by monperrus** [comment]
Only Assert4j is not supported now.
