### ISSUE TITLE
Refactoring of InputConfiguration Class for maven plugin usage

### ISSUE THREAD

**Issue by nicolabertazzo** [STAMP-project/dspot#245]
In order to use dspot as a maven plugin I want to use [the InputConfiguration Class](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/fr/inria/diversify/utils/sosiefier/InputConfiguration.java) to get the parameter from  pom.xml file.
So I propose tu refactor this calass so we can use It to read parameter from pom file.

**Comment by danglotb** [comment]
Hi @nicolabertazzo do you plan any more changes on the `InputConfiguration` object?

**Comment by nicolabertazzo** [comment]
Yes after the in person meeting

**Comment by danglotb** [comment]
Does this issue duplicate #392?
