### ISSUE TITLE
DSpot Usage: describe a test-project-centric (rather than DSpot-centric) usage of DSpot

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#246]
**Issue Type**: Enhancement
**Description**: Current [DSpot for dummies tutorial](https://github.com/STAMP-project/dspot/blob/master/docs/dspot-for-dummies.md), but also implicit in the dspot.properties promotes a Dspot-centric usage, where the location of DSpot project (GitHub clone) is relevant, but DSpot should be a library used from the case project location it is going to be used for amplification. Therefore, DSpot should be launched from an script or IDE, or adopting Maven/Gradle, from the user project location, being only the DSpot Jar (or classpath) location relevant. 

In this way, in dspot.properties, project points to current folder, or it could even removed
> #relative path to the project root from dspot project
> project=./

And DSpot could be invoked directly in the test project by referring to the DSpot Library location:

> #!/bin/sh
> DSPOT_JAR=/home/yosu/Projects/STAMP/Git/dspot/target/dspot-1.0.0-jar-with-dependencies.jar
> java -Dis.admin.user=admin -Dis.admin.passwd=$2pRSid# -jar $DSPOT_JAR -p ./dspot2.properties \
> -i 1 -t eu.supersede.integration.api.replan.controller.proxies.test.ReplanControllerProxyTest \
> -a MethodAdd -s JacocoCoverageSelector --verbose

so, the dspot-out/ folder is placed within the test project, not in DSpot project location.
**Reproducibility**: always
**Severity**: feature
**Tool**: DSpot, version 26/10/17
**Execution Environment**: Linux OpenSuse Tumbleweed
**Steps to reproduce**: N/A
**Files**:
**Relationships**: 
**Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

This is because, at the start, **DSpot** had to be launch from the main **DSpot**, but now, it can be launch from everywhere, and thus from the target project folder.

The current documentation has not been updated, since a while.

In addition to this, @nicolabertazzo is working on a maven-plugin. It is much more comfortable to run **DSpot**.

Cheers,

-- Benjamin.

**Comment by jesus-gorronogoitia** [comment]
Yes, it is only a documentation-related issue. Indeed I've launched DSpot as commented in the description, and it worked fine. In WP4 we will work as well to support DSpot and Descartes from Eclipse IDE

**Comment by monperrus** [comment]
@jesus-gorronogoitia would you make a PR on documentation or do we close this issue? Thanks.

**Comment by jesus-gorronogoitia** [comment]
I guess it is Benjamin who has to answer, or do you want me to modify DSpot documentation?

**Comment by monperrus** [comment]
> do you want me to modify DSpot documentation?

if it is possible for you, that would be great. Pull requests on documentation are much welcome.

**Comment by jesus-gorronogoitia** [comment]
Sure, I will do it during next Madrid meeting, so in case of doubt, I can discuss it with Benjamin.

**Comment by monperrus** [comment]
super, thanks.

the goal here is to clean old tickets.

**Comment by danglotb** [comment]
Closed with #297 

Thank you very much @jesus-gorronogoitia !
