### ISSUE TITLE
Error while running mvn test

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/dspot#250]
Trying to run mvn test, almost all tests pass except the error below:

```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.106 sec - in fr.inria.diversify.mutant.pit.PitTest

Results :

Failed tests: 
  AssertGeneratorTest.testGenerateAssert:51 expected:<...sWithBoolean();
    [// AssertGenerator add assertion
    org.junit.Assert.assertTrue(((fr.inria.sample.ClassWithBoolean)cl).getBoolean());
    // AssertGenerator add assertion
    org.junit.Assert.assertTrue(((fr.inria.sample.ClassWithBoolean)cl).getTrue());
    // AssertGenerator add assertion
    org.junit.Assert.assertFalse(((fr.inria.sample.ClassWithBoolean)cl).getFalse());
    ]cl.getFalse();
    c...> but was:<...sWithBoolean();
    []cl.getFalse();
    c...>

Tests in error: 
  MethodsAssertGeneratorTest.testBuildNewAssert:72 » UnsupportedOperation

Tests run: 83, Failures: 1, Errors: 1, Skipped: 0
```
Environment: OpenJDK 1.8, Maven 3.5.2, Ubuntu 16

**Comment by danglotb** [comment]
Hi @slauriere 

Are you using the last version of **DSpot**?

It seems that your expected value is quite old (see [this](https://github.com/STAMP-project/dspot/blob/master/dspot/src/test/java/fr/inria/diversify/dspot/assertGenerator/AssertGeneratorTest.java#L42)). 

Could you provide the full trace of the execution of the `mvn test`?

If you want to run **DSpot**, you can still download the [release](https://github.com/STAMP-project/dspot/releases).

Thank you,

Cheers.

**Comment by slauriere** [comment]
Thanks @danglotb, I was actually not using the master branch, by mistake, I'm closing this issue and I'll use the release indeed.
