### ISSUE TITLE
feat: add support for Junit5

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#256]
Hi, I've tried to run DSpot on XWiki, precisely on `xwiki-commons/xwiki-commons-core/xwiki-commons-text` (https://github.com/xwiki/xwiki-commons/tree/master/xwiki-commons-core/xwiki-commons-text).

Here's what I did:

* clone Dspot and build it
* Added a dspot.properties file with the following content:

```
project=../../
targetModule=xwiki-commons-core/xwiki-commons-text/
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=output
filter=org.xwiki.*
```

* Executed `java -cp /Users/vmassol/dev/dspot/dspot/target/dspot-1.0.1-SNAPSHOT-jar-with-dependencies.jar  fr.inria.stamp.Main --path-to-properties dspot.properties` 

I got:

```
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-text (master) $ java -cp /Users/vmassol/dev/dspot/dspot/target/dspot-1.0.1-SNAPSHOT-jar-with-dependencies.jar  fr.inria.stamp.Main --path-to-properties dspot.properties
2017-12-05 14:39:19,706 INFO fr.inria.diversify.automaticbuilder.AutomaticBuilderFactory - Selected Maven automatic builder.
2017-12-05 14:39:19,720 INFO fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder - run maven dependency:build-classpath -Dmdep.outputFile=target/dspot/classpath
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
2017-12-05 14:39:22,646 INFO fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder - run maven  org.pitest:pitest-maven:mutationCoverage -DwithHistory -DtargetClasses=org.xwiki.* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/ 
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
2017-12-05 14:39:25,636 INFO fr.inria.stamp.coverage.JacocoExecutor - The original test suite kill 0 / 119
207 ms
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-text (master) $
```

There are no errors but I'm not sure what to do with the result... :)

**Comment by vmassol** [comment]
Maybe some section about analyzing the results on https://github.com/STAMP-project/dspot would help?

**Comment by danglotb** [comment]
Hi,

It is because tests inside of `xwiki-commons-text` are not considered as tests.

After investigations, it is because it's **JUnit5**, and **DSpot**. does not support yet **JUnit5**.

I'll try to support it.

**Comment by danglotb** [comment]
There is two problem:

1. PIT does not support **JUnit5**
2. It seems that we have to implements a new test runner

**Comment by monperrus** [comment]
renamed issue to "feat: add support for Junit5"

**Comment by monperrus** [comment]
related: see the Pit plugin https://github.com/pitest/pitest-junit5-plugin

would it help us for supporting Junit5?

**Comment by vmassol** [comment]
@danglotb hi, I noticed https://github.com/STAMP-project/dspot/commit/54dcac21a3044ceb26b1e0317f534313fc0855d9 Does it mean DSpot now supports JUnit5 or is this not finished yet?

**Comment by danglotb** [comment]
HI @vmassol 

It should support JUnit5, or at least, convert the `@Test` of JUnit5 to a `@Test` of JUnit4.

**DSpot** will output JUnit4 test method(s).

**Comment by vmassol** [comment]
Ok so I doubt it will work in the majority of cases

**Comment by vmassol** [comment]
There's no easy conversion of JUnit5 to JUnit4. Will fail in most cases for xwiki.

**Comment by vmassol** [comment]
So we cannot say that JUnit5 is supported yet I think.

**Comment by vmassol** [comment]
Anyway we'll try and report issues. Thanks!

**Comment by danglotb** [comment]
This has been resolved with recent changes.
