### ISSUE TITLE
Improve documentation for using DSpot

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#258]
* Mention the option to download dspot
* Reorganizing to put the usage on your own project first
* Align to 120 chars
* Fix markdown syntax errors
* Provide more explanations for creating your own dspot properties file and especially in a maven use case.

**Comment by vmassol** [comment]
PR available at https://github.com/STAMP-project/dspot/pull/259

**Comment by monperrus** [comment]
closed per #259
