### ISSUE TITLE
feat: add support for generated test with autoimport

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#262]
idea: reload the generated tests at the very end in spoon and pretty-print them in auto-import.

**Comment by monperrus** [comment]
today, in our Claremont meeting, the generated tests are fully-qualified.
 
reopening this issue.

**Comment by danglotb** [comment]
It happens because DSpot tries to compile at the end of the process and if it does not succeed, it prints the amplified test class using fullqualified names (no imports) in order to avoid problems when reusing the amplified test class.

I'm looking at why there are some compilation errors.
