### ISSUE TITLE
Failure on com.telefonica.iot.cygnus: excludedClasses doesn't work properly 

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/dspot#277]
**Issue Type**: bug

**Description**: 
Can't amplified multiple tests. It's mandatory to have a green suit to pass all test but, in order to skip all fail tests I used the variable excludedClasses but doesn't works too.

> 2017-12-05 19:38:36,965 INFO fr.inria.diversify.automaticbuilder.AutomaticBuilderFactory - Selected Maven automatic builder.
2017-12-05 19:38:54,216 INFO fr.inria.diversify.dspot.Amplification - amplification of com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest (1 test)
2017-12-05 19:38:56,345 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting max total connections (50)
2017-12-05 19:38:56,349 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting default max connections per route (10)
2017-12-05 19:38:56,379 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting max total connections (50)
2017-12-05 19:38:56,381 INFO com.telefonica.iot.cygnus.backends.http.HttpClientFactory - Setting default max connections per route (10)
Testing CKANBackendImpl.persist
2017-12-05 19:38:56,530 INFO fr.inria.diversify.dspot.Amplification - update test testCriterion
2017-12-05 19:38:56,530 INFO fr.inria.diversify.dspot.Amplification - Try to add assertions before amplification
2017-12-05 19:38:57,404 WARN fr.inria.stamp.coverage.JacocoExecutor - Some test(s) failed during computation of coverage:
com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest:
Mockito cannot mock this class: class com.telefonica.iot.cygnus.backends.ckan.CKANCache.

>Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

>Java : 1.8
JVM vendor name : Oracle Corporation
JVM vendor version : 25.151-b12
JVM name : Java HotSpot(TM) 64-Bit Server VM
JVM version : 1.8.0_151-b12
JVM info : mixed mode
OS name : Linux
OS version : 4.10.0-40-generic

>Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
2017-12-05 19:38:58,040 WARN fr.inria.stamp.coverage.JacocoExecutor - Some test(s) failed during computation of coverage:
com.telefonica.iot.cygnus.backends.ckan.CKANBackendImplTest:
Mockito cannot mock this class: class com.telefonica.iot.cygnus.backends.ckan.CKANCache.

>Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

>Java : 1.8
JVM vendor name : Oracle Corporation
JVM vendor version : 25.151-b12
JVM name : Java HotSpot(TM) 64-Bit Server VM
JVM version : 1.8.0_151-b12
JVM info : mixed mode
OS name : Linux
OS version : 4.10.0-40-generic
Underlying exception : java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException at fr.inria.stamp.Main.amplifyOne(Main.java:94) at fr.inria.stamp.Main.lambda$run$0(Main.java:68) at java.util.Arrays$ArrayList.forEach(Arrays.java:3880) at fr.inria.stamp.Main.run(Main.java:64) at fr.inria.stamp.Main.main(Main.java:38) Caused by: java.lang.NullPointerException at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.lambda$selectToAmplify$0(JacocoCoverageSelector.java:66) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.selectToAmplify(JacocoCoverageSelector.java:73) at fr.inria.diversify.dspot.Amplification.preAmplification(Amplification.java:183) at fr.inria.diversify.dspot.Amplification.amplification(Amplification.java:75) at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:187) at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:169) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:157) at fr.inria.stamp.Main.amplifyOne(Main.java:89) ... 4 more

**Reproducibility**: always 

**Severity**: major

**Tool**: DSpot latest version

**Execution Environment**: Linux Ubuntu 16.04

**Steps to reproduce**:
`[root@osboxes dspot]# java -Xms4G -jar target/dspot-1.0.2-jar-with-dependencies.jar -p ../../fiware-cygnus/cygnus-common/fiware.properties -i 1 -t com.telefonica.iot.cygnus.* -a MethodAdd -s JacocoCoverageSelector`
**Files**:
properties.file

> #relative path to the project root from dspot project
project=../../fiware-cygnus/cygnus-common
#relative path to the source project from the project properties
src=src/main/java/
#relative path to the test source project from the project properties
testSrc=src/test/java
#java version used
javaVersion=8
#(optional) path to the output folder, default to "output_diversify"
outputDirectory=fiware-out/
#(optional) filter on the package name containing tests to be amplified ("example" => "example.")
filter=com.telefonica.iot.cygnus
#(optional) filter on the package name containing tests to be excluded
#excludedClasses=my.class.TestClass,my.pacakage.*
excludedClasses=CKANBackendImplTest,com.telefonica.iot.cygnus.backends.ckan.*
,HDFSBackendImplBinaryTest,com.telefonica.iot.cygnus.backends.hdfs.*
,MySQLBackendImplTest,com.telefonica.iot.cygnus.backends.mysql.*
,PostgreSQLBackendImplTest,com.telefonica.iot.cygnus.backends.postgresql.*
,ManagementInterfaceTest,com.telefonica.iot.cygnus.management.*
,MetricsHandlersTest,com.telefonica.iot.cygnus.management.*
,CygnusMetricsTest,com.telefonica.iot.cygnus.utils.*

**Relationships**: https://github.com/telefonicaid/fiware-cygnus

**Reporter**: Fernando Méndez Requena fernando.mendez.external@atos.net

**Comment by danglotb** [comment]
Hi @fermenreq 

> 2017-12-05 19:38:57,404 WARN fr.inria.stamp.coverage.JacocoExecutor - Some test(s) failed during computation of coverage:

The failure happens when **DSpot** uses Jacoco to compute the coverage.

The JacocoCoverageSelector does not use the property `excludedClasses` (it should but it does not yet).

In addition to this, your test is a mockito test, which are uncompatible with Jacoco see this [thread](https://github.com/mockito/mockito/issues/969).

I suggest you to change your selector _i.e._ using the PitMutantScoreSelector instead of JacocoCoverageSelector.

Thank you.

**Comment by fermenreq** [comment]
Hi @danglotb :
Reading the readme, PitMutantScoreSelector is set on by default. Otherwise it failed cause no mutations was found

Thanks

**Comment by monperrus** [comment]
can we close this one?

**Comment by fermenreq** [comment]
Hi @monperrus, is still not working

`root@osboxes:/home/osboxes/Desktop/STAMP/dspot/dspot# java -Xms4G -jar target/dspot-1.0.2-SNAPSHOT-jar-with-dependencies.jar -p ../../fiware-cygnus/cygnus-common/fiware.properties -i 1 -t com.telefonica.iot.cygnus.* -a MethodAdd -s PitMutantScoreSelector`

I set up pom.xml file, in order to include some mutators

> <plugins>
        <plugin>
             <groupId>org.pitest</groupId>
                 <artifactId>pitest-maven</artifactId>
             <version>Latest</version>
               <configuration>
                     <mutators>
                         <mutator>CONSTRUCTOR_CALLS</mutator>
                         <mutator>NON_VOID_METHOD_CALLS</mutator>
                     </mutators>
              </configuration>
        </plugin>

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.080 s
[INFO] Finished at: 2017-12-06T04:34:13+01:00
[INFO] Final Memory: 16M/67M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.2.5:mutationCoverage (default-cli) on project cygnus-common: Execution default-cli of goal org.pitest:pitest-maven:1.2.5:mutationCoverage failed: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
[ERROR] See http://pitest.org for more details.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
    at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:179)
    at fr.inria.diversify.dspot.selector.PitMutantScoreSelector.init(PitMutantScoreSelector.java:59)
    at fr.inria.diversify.dspot.DSpot.<init>(DSpot.java:105)
    at fr.inria.stamp.Main.run(Main.java:55)
    at fr.inria.stamp.Main.main(Main.java:38)
Caused by: java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
    at fr.inria.diversify.automaticbuilder.MavenAutomaticBuilder.runPit(MavenAutomaticBuilder.java:176)
    ... 4 more

**Comment by danglotb** [comment]
HI,

Could you please, give the part of the traces just above of what you posted? To see actually which tests is failing.

Thank you.

**Comment by monperrus** [comment]
Why do you have some pitest configuration?

DSpot does not need any Pit configuration.

Can you try with a standard fresh Dspot install?

**Comment by monperrus** [comment]
ping @fermenreq?
