### ISSUE TITLE
Generated tests is not compiling for DefaultHTMLCleanerTest

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#280]
Original test: https://github.com/xwiki/xwiki-commons/blob/master/xwiki-commons-core/xwiki-commons-xml/src/test/java/org/xwiki/xml/internal/html/DefaultHTMLCleanerTest.java

Generated failing test: https://gist.github.com/vmassol/cbc33713f00f327d546aad007fa00b4f

Errors:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-xml/target/dspot-output/org/xwiki/xml/internal/html/AmplDefaultHTMLCleanerTest.java:[636,37] cannot find symbol
  symbol: variable cleaner
[ERROR] /Users/vmassol/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-xml/target/dspot-output/org/xwiki/xml/stax/AmplStAXUtilsTest.java:[420,37] cannot find symbol
  symbol: variable cleaner
[INFO] 2 errors 
```

**Comment by vmassol** [comment]
Executed with: `java -cp /Users/vmassol/dev/dspot/dspot/target/dspot-1.0.2-SNAPSHOT-jar-with-dependencies.jar fr.inria.stamp.Main --path-to-properties dspot.properties --verbose -i 1 --amplifiers TestDataMutator:MethodAdd:MethodRemove:StatementAdd` on xwiki-commons-xml

**Comment by danglotb** [comment]
> /* amplification of org.xwiki.xml.html.HTMLUtilsTest#testStripTopLevelParagraph */

It seems that **DSpot** adds amplified tests from other test classes.

Going to fix ASAP.
