### ISSUE TITLE
Add an option to not add original test methods inside amplified tests classes

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#285]
Rationale:
* Needed when you want to commit the generated tests in a different test source root, next to the existing manually written tests
* Otherwise:
  * More time to execute with no aded value
  * Harder to see what new stuff was added

**Comment by danglotb** [comment]
This feature has been added with f7305a3203745f0e79e126c37843d1eaa73c9041, but it is now the default behavior of **DSpot**.
