### ISSUE TITLE
Dspot doesn't seem to overwrite already generated tests

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#286]
For ex I ran dspot with various CLI parameters and I noticed that my second run didn't overwrite the existing dspot-generated files.

Found on DSpot 1.0.4-SNAPSHOT (built from sources on 13 dec, 16:00).

**Comment by danglotb** [comment]
Instead of overwrite existing result, users can choose to delete (if exist) the output directory with the --clean flag.

Users can also keep this directory (by default) to stack result between runs.

**Comment by danglotb** [comment]
see #313
