### ISSUE TITLE
--useReflection doesn't work

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#287]
Happens on v1.0.4-SNAPSHOT built from sources on 13 dec, 16:00.

Issue found on xwiki-commons-xml

**Comment by monperrus** [comment]
it's not even a regression, it has probably never worked :-)

**Comment by danglotb** [comment]
This feature won't be implemented since we will use a test runner that launch a new JVM.

see #301

**Comment by monperrus** [comment]
Should we remove the flag from the code and the documentation then?

**Comment by danglotb** [comment]
see #321 .
