### ISSUE TITLE
Failure creating jar

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#303]
Hi,
When  running `mvn package`I have an error, I attached the output.
I am using latest dspot release.
Thanks for your help.
[output.txt](https://github.com/STAMP-project/dspot/files/1651621/output.txt)

**Comment by danglotb** [comment]
Hi @assadOW2 

> I am using latest dspot release.

You get the source code of the latest release? You can use directly the jar available `dspot-1.0.5-jar-with-dependencies.jar`.

Anyway, to solve your problem, you should run `mvn clean package`.

In fact, during the execution of tests, **DSpot** generates some files, which make the compilation failing.

Sorry about that, we should clean those files after the execution of the tests.

-- Benjamin.

**Comment by assadOW2** [comment]
Hi Benjamin,

Thanks for the quick reply. 
I still have the same error after cleaning, here is the verbose output I have after 

 `mvn clean package`

[output.txt](https://github.com/STAMP-project/dspot/files/1652041/output.txt)

But I will download the jar and use it directly as you advise me.

**Comment by danglotb** [comment]
Hi @assadOW2 

Okay your error is known, and will be fixed with #302.

Thank you very much for using **DSpot**!

-- Benjamin.

**Comment by assadOW2** [comment]
Ok so I close this issue.

Thanks.
