### ISSUE TITLE
Make clear in the README that dspot only works on maven and gradle projects

### ISSUE THREAD

**Issue by danielleberre** [STAMP-project/dspot#314]
I just tried to run dspot on a simple java project built using ant.

dspot  fails because it does not find a maven pom.xml file in the project.

One should make clear in the README that dspot targets only java projects built using maven or gradle.

**Comment by danglotb** [comment]
Hi @danielleberre 

**DSpot** can be run on Maven (by default) and Gradle (See the `--automatic-builder`) projects.

Thank you for the suggestion to improve the documentation. see #316
