### ISSUE TITLE
Simplify the command line for the user using java -jar in whole README

### ISSUE THREAD

**Issue by danielleberre** [STAMP-project/dspot#318]
The README proposes to run the software using the Main class of the project.

`java -cp /path/to/dspot-*-jar-with-dependencies.jar fr.inria.stamp.Main`

Those details are usually hidden to the user with an executable jar command.

`java -jar /path/to/dspot-LATEST-jar-with-dependencies.jar`

This is actually the command used in the getting started section.

I would suggest to use the latter uniformly in the README

**Comment by danglotb** [comment]
Thank for the suggestions to improve the documentation!
