### ISSUE TITLE
add in the README documentation about the internal API

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#325]
there are cases when one wants to use DSpot as a library and not as a command-line tool.

for that, we should add in the README documentation about the internal API of the main DSpot class.

issue raised by @jesus-gorronogoitia

**Comment by jesus-gorronogoitia** [comment]
Thanks Martin,
I've asked my colleague Ricardo to investigate DSpot internal API, by investigating the DSpot CLI class that gets the user input.
This is not required by use cases but by WP4, where we are implemented Eclipse IDE support for most of the STAMP tools.

**Comment by monperrus** [comment]
OK. It seems to me that having a good documentation will be useful beyond the integration in Eclipse.

**Comment by danglotb** [comment]
Hi all, I started a PR to add this to the README.

Please, find it [here](https://github.com/danglotb/dspot/blob/readme-api/README.md), the preview on my branch will be fancier that reading directly the markdown :)

WDYT?

Cheers.

**Comment by monperrus** [comment]
That's really good. I've made minor changes.

I'm OK to merge it and close the issue, we could still improve it after.

Thanks a lot Benjamin.

**Comment by danglotb** [comment]
I'm ok to merge too!

@jesus-gorronogoitia I let you to merge!

**Comment by jesus-gorronogoitia** [comment]
Bonjour,
One questions about API documentation:
1- Do you refer to the relative path, from current Java execution dir, or to the absolute path?
> First of all, you have to create an InputConfiguration. Only the path to your properties is required
I guess it is relative, as the CLI also requires a relative path from the execution point.

Do you want me to accept your pull request? I am ok with your documentation, which looks pretty clear and complete, but I don't think I can proceed accepting  your PR, as it seems I have not rights for that when I get access there.

**Comment by danglotb** [comment]
> 1- Do you refer to the relative path, from current Java execution dir, or to the absolute path?

I guess both. When you instanciate an `InputConfiguration`, you need to specify where is the the properties file.

> Do you want me to accept your pull request? I am ok with your documentation, which looks pretty clear and complete, but I don't think I can proceed accepting your PR, as it seems I have not rights for that when I get access there.

I checked, and the invitation is pending. Before having any right to merge, you have to accept this invitation. 

I will cancel the invitation and re-invite you, by doing this, github will send you a mail with the invitation link. 

Once you accept the invitation, will be able to merge the PR.

Thank you.

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia ,

Now that you have right to push on the repository, you just need to click on the green button of the #326, `Squash and Merge`.

`Squash and Merge` means that GitHub will put all our commits into one, and push this single commit on the master branch.

For me, the default message is good: it keeps the history and carry well the purpose of the pr, however you can change it, if you judge that it is required.

**Comment by monperrus** [comment]
closed per #326 
thanks!
