### ISSUE TITLE
Discarding partially failing amplified test classes

### ISSUE THREAD

**Issue by sbihel** [STAMP-project/dspot#336]
https://github.com/STAMP-project/dspot/blob/94bb8d27fdc241fd88ab90562128ba656db8e062/dspot/src/main/java/fr/inria/diversify/dspot/Amplification.java#L126

This branch is never taken because `compileAndRunTests` returns `null` if at least one test is failing.

https://github.com/STAMP-project/dspot/blob/94bb8d27fdc241fd88ab90562128ba656db8e062/dspot/src/main/java/fr/inria/diversify/dspot/Amplification.java#L236

**Comment by danglotb** [comment]
Hi @sbihel 

You would mind to propose a PR that fix this? 

Cheers.

**Comment by sbihel** [comment]
Ok!
