### ISSUE TITLE
Default PitMutantScoreSelector selector does not work

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#379]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot compiled version 27/03/18
- **Execution Environment**: Linux Opensuse Tumbleweed
- **Reporter**: Jesús Gorroñogoitia: <jesus.gorronogoitia@atos.net>

#### Description
Dspot default selector: PitMutantScoreSelector does not work, triggering an exception.
If this is a known issue and this selector is going to be deprecated, please, replace the default selector by another one that works well.
My colleague Ricardo has reported me that this selector works well in Windows. For him, other selector as Clover or Jacoco are not working in Windows. In my case (Linux) is the another way around: PitMutantScoreSelector is not working, while the other two are.
 
#### Steps to reproduce
Clean/build DSpot from sources
Use Dhell project. Execute Dspot using ./run_dspot.sh script. 

#### Other files and URLs
[dspot.txt](https://github.com/STAMP-project/dspot/files/1852725/dspot.txt)

#### Relationships
N/A

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

I choose to put the `PitMutantScoreSelector` because I believe that increasing the mutation score and so, the ability of the test suite to catch bug is the main interest of **DSpot**.

According to your traces, the problem comes from **PIT** and not from **DSpot**. On my side everything works well.

Do you have internet when you run **DSpot**? Because it uses the maven plugin of **PIT**, and it might try to download dependencies.

You did use this selector in your previous experiments, right? It did not move since. Since I cannot reproduce the error, It is hard for me to understand the root cause.

**Comment by jesus-gorronogoitia** [comment]
Yes, I have Internet access all time. An yes, it worked with DHell before, not any more. And yes, it is a PIT issue, complaining about some missing class dependency. 
I will follow again the DSpot documentation with DHell. I will let you know if the problem persists.
No complains about PitMutantScoreSelector as default one if it is working, but I remember in another issue you recommend me Clover or Jacoco over Pit one.

**Comment by jesus-gorronogoitia** [comment]
Still not working. Are you testing Dhell with run_dspot.sh? Could it be related to the fact that pom.xml in that folder contains a configuration for Descartes that references PITest maven plugin 1.2.0?

**Comment by danglotb** [comment]
Yes, I tried on dhell and used the provided script `run_dspot.sh`. 

>  Could it be related to the fact that pom.xml in that folder contains a configuration for Descartes that references PITest maven plugin 1.2.0?

Yes It could be, but on my side, I have the following pom: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>eu.stamp.examples</groupId>
  <artifactId>hello_app</artifactId>
  <version>1.2.1</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <default.encoding>UTF-8</default.encoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
    </dependency>

    <dependency>
      <groupId>org.pitest</groupId>
      <artifactId>pitest-maven</artifactId>
      <version>1.3.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>eu.stamp</groupId>
        <artifactId>pitmp-maven-plugin</artifactId>
        <version>1.1.1</version>
        <!--
        -->
        <configuration>
          <targetClasses>
            <param>eu.stamp.examples.dhell*</param>
          </targetClasses>
          <excludedClasses>
            <param>eu.stamp.examples.dhell.MyLogger</param>
          </excludedClasses>
          <excludedMethods>
            <param>eu.stamp.examples.dhell.MyStorage.deleteFile</param>
            <param>eu.stamp.examples.dhell.HelloApp.myPrint</param>
            <param>eu.stamp.examples.dhell.HelloApp.cardMyTraces</param>
            <param>eu.stamp.examples.dhell.HelloApp.getMyTraces</param>
          </excludedMethods>
        </configuration>
      </plugin>

      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.0.0</version>
        <configuration>
          <filesets>
            <fileset>
              <directory>.</directory>
              <includes>
                <include>*.txt</include>
                <include>*.traces</include>
                <include>*.log</include>
              </includes>
              <followSymlinks>false</followSymlinks>
            </fileset>
          </filesets>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
```

**Comment by jesus-gorronogoitia** [comment]
With your pom.xml it works, thanks. I guess the reason was that I added Descartes configuration, which is incompatible with DSpot.
