### ISSUE TITLE
MethodAssertGenerator: makeFailureTest()

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#39]
Hello, I open this issue to discuss about the [makeFailureTest()](https://github.com/STAMP-project/dspot/blob/master/src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodAssertGenerator.java#L113) method.

It builds a try/catch block with a fail statement at the end. That is to say, the oracle is to expect the program to throw an exception, example:

```java
/* amplification of example.TestSuiteExample#test3 */
    @org.junit.Test(timeout = 1000)
    public void test3_cf118_literalMutation136() {
        // AssertGenerator generate try/catch block with fail statement
        try {
            example.Example ex = new example.Example();
            java.lang.String s = "abcd";
            // StatementAdderOnAssert create random local variable
            int vc_17 = 630434226;
            // AssertGenerator add assertion
            org.junit.Assert.assertEquals(vc_17, 630434226);
            // StatementAdderOnAssert create random local variable
            java.lang.String vc_15 = new java.lang.String();
            // AssertGenerator add assertion
            org.junit.Assert.assertEquals(vc_15, "");
            // StatementAdderMethod cloned existing statement
            ex.charAt(vc_15, vc_17);
            // MethodAssertGenerator build local variable
            Object o_10_0 = ex.charAt(s, ((s.length()) - 1));
            junit.framework.TestCase.fail("test3_cf118 should have thrown StringIndexOutOfBoundsException");
        } catch (java.lang.StringIndexOutOfBoundsException eee) {
        }
    }
```

IHMO, It is a very weak oracle and I would like to have your opinion about it:

Should we discard this case, and just drop the makeFailureTest() method, 

or it worth it to have this kind of test cases? (for now DSpot generates a lot of this kind of test cases, maybe we should at least reduce/limit this number).

**Comment by monperrus** [comment]
if they kill more mutants, I'd say that they are very interesting.
Do you have empirical figures?

**Comment by danglotb** [comment]
Ok, just got some new results on javapoet. Indeed such tests kill mutants, so we keep them.
We double the number of mutants killed with them (from 3 without to 6).
