### ISSUE TITLE
Remove relative path in Dspot InputConfiguration

### ISSUE THREAD

**Issue by nicolabertazzo** [STAMP-project/dspot#392]
#### Characteristics
- **Issue Type**: [feature]
- **Severity**: [feature]
- **Reporter**: [Nicola Bertazzo, nicola.bertazzo@eng.it]

#### Description
In dspot/dspot/src/main/java/fr/inria/diversify/utils/sosiefier/InputConfiguration.java the file path of some properties (testSrc, src, classes, tmpDir) are stored as relative path (String). My proposal is to store these properties as absolute path or File.
#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @nicolabertazzo 

Are you working on this?

I could have a look, I'll refactor `InputConfiguration` and `InputProgram` objects to unify them.

**Comment by nicolabertazzo** [comment]
No i'm fixing some problem about maven plugin (adding the new in line parameters).
I'll update InputConfiguration before the end of this week.

**Comment by nicolabertazzo** [comment]
Hi @danglotb ,
I fixed some problems about inputConfiguration refactoring and [I pushed to master](https://github.com/STAMP-project/dspot/commit/d3181d35d4fce46d357f477f4ad03c3796ba20a3).
I have an issue when i run dspot from maven on dhell.
If i execute from dhell folder the follow command:

`mvn clean test eu.stamp-project:dspot-maven:1.1.1-SNAPSHOT:amplify-unit-tests -Diteration=3 -Dtests=eu.stampproject.examples.dhell.HelloAppTest -Dfilter=eu.stamp_project.examples.dhell*`

The result is:

` The original test suite kill 114 / 371`

But if i execute dspot from pit using this command:

`mvn org.pitest:pitest-maven:1.3.0:mutationCoverage -DwithHistory -DtargetClasses=eu.stamp_project.examples.dhell* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/ `

the result is different.

@danglotb  can you check if dspot runs correctly from maven?

**Comment by danglotb** [comment]
>the result is different.

What do you mean? The original test suite does not kill 114 mutants over 371?

> I fixed some problems about inputConfiguration refactoring and I pushed to master.

please, do not push directly on master, but rather open a pull request.

**Comment by nicolabertazzo** [comment]
The original test suite generate this result:
`>> Generated 371 mutations Killed 120 (32%)
>> Ran 5 tests (0.01 tests per mutation)
=========================================`

I'm sorry if I pushed into the master. It was a mistake.

**Comment by danglotb** [comment]
The difference is not significative. Thus, the number of generates mutants is the same.

The difference in the killed mutant can come from TIMED_OUT execution or MEMORY errors.

It would be great if you can provide the `.csv` files.

**Comment by danglotb** [comment]
This has been fixed with recent changes.
