### ISSUE TITLE
add support for focused test amplification

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#399]
we would say: improve tests that specify class "Foo" or method "Foo#m()" (because "Foo" or method "Foo#m()" are poorly tested)

**Comment by oscarlvp** [comment]
At the moment we could focus on the specific sub-problem where the method is pseudo-tested.
We can set up a workflow in which we first detect the test classes which are closer to the method and then target these test classes with DSpot and using the `PitMutantScoreSelector` with Descartes as mutation engine.

**Comment by danglotb** [comment]
This is has been resolved in [STAMP-project/reneri](https://github.com/STAMP-project/reneri). Closing.
