### ISSUE TITLE
Dspot on Sat4j not finishing

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#415]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: dspot-1.1.0
- **Execution Environment**: Linux Ubuntu 16.04
- **Reporter**: Assad Montasser, assad.montasser@ow2.org

#### Description

I am running Dspot on Sat4j project, component "core": https://gitlab.ow2.org/sat4j/sat4j/tree/master/org.sat4j.core

I have an output folder but the execution crashes before end. I attached output log of the verbose execution of Dspot.

Initial project mvn install ok.

My dspot.properties:
```
project=.
filter=org.sat4j.core.*
src=src/main/java/
testSrc=src/test/java
javaVersion=8
outputDirectory=dspot-out/
timeoutConstInMillis=10000
jvmArgs=['-Xmx2048m','-Xms1024m']
```

#### Steps to reproduce
```
java -jar /home/assadm/STAMP-project/dspot/dspot-1.1.0-jar-with-dependencies.jar --path-to-properties dspot.properties --verbose --clean
```

#### Other files and URLs
[output.log](https://github.com/STAMP-project/dspot/files/1973934/output.log)

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @assadOW2 

**DSpot** is not able to compile the tests. I'm gonna investigate in the next week to debug this. Thank you!

I would like to say that I made a mistake when explaining the properties.

Your property were well configured according to the project, _i.e._ the **targetModule** property was ok (however, naming modules as packages is unconventional, right?)

Anyway, specifying the filter is very recommended.

I'll keep you update of my progress.
