### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException 	at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.report(JacocoCoverageSelector.java:175)

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#426]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot latest 1.1.1 SNAPSHOT
- **Execution Environment**: CentOS 7
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot stops with exception after a while amplifying eu.supersede.integration.api.adaptation.proxies.test.* tests for Supersede IF component:

> Exception in thread "main" java.lang.NullPointerException
> 	at fr.inria.diversify.dspot.selector.JacocoCoverageSelector.report(JacocoCoverageSelector.java:175)
> 	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:190)
> 	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:165)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at fr.inria.diversify.dspot.DSpot.amplifyTest(DSpot.java:161)
> 	at fr.inria.diversify.dspot.DSpot.lambda$amplifyAllTestsNames$2(DSpot.java:136)
> 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at fr.inria.diversify.dspot.DSpot.amplifyAllTestsNames(DSpot.java:137)
> 	at fr.inria.stamp.Main.run(Main.java:78)
> 	at fr.inria.stamp.Main.run(Main.java:92)
> 	at fr.inria.stamp.Main.main(Main.java:41)

#### Steps to reproduce
See experiment description below. Test executed over [Supersede IF](https://github.com/supersede-project/integration/tree/descartes/IF/API/eu.supersede.if.api) component using [executeSpot.sh](https://github.com/supersede-project/integration/blob/descartes/IF/API/eu.supersede.if.api/executeDSpot.sh) script, with run configuration:
```
DSpot CMI configuration:  -i 3 -t eu.supersede.integration.api.adaptation.proxies.test.* -a MethodAdd:StatementAdd:TestDataMutator -s JacocoCoverageSelector --verbose
DSpot properties file:  ./dspot.properties
```
#### Other files and URLs
See complete execution log (file dspot_if_date.txt) in [experiment](https://github.com/STAMP-project/dspot-usecases-output/tree/master/atos/supersede/JacocoCoverageSelector/MethodAdd:StatementAdd:TestDataMutator/2018-05-10_10:37:00) folder:

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
I am getting the same NPE when using DSpot to amplify other IF test cases, for instance: eu.supersede.integration.api.adaptation.proxies.test.*

**Comment by jesus-gorronogoitia** [comment]
I checked that for other IF test cases, DSpot complete the process without errors. For instance: eu.supersede.integration.api.analysis.proxies.test.*

**Comment by danglotb** [comment]
It seems that your both issues (this one and #425) are related.

The root cause is `eu.supersede.integration.api.adaptation.proxies.test.AdapterProxyTest#testEnactSelectedAdaptationDecisionsInFCGivenByString` according to the logs: 

>Timeout during execution of eu.supersede.integration.api.adaptation.proxies.test.AdapterProxyTest: testEnactSelectedAdaptationDecisionsInFCGivenByString

I don't know why this test is failing, even by increasing the time out value.

I'll investigate further.

**Comment by danglotb** [comment]
Okay, the documentation is still wrong...

The way to increase the timeout is by using the command line option `--timeOut <integer>` and not the old property `timeoutConstInMillis`.

On my side, I used `--timeOut 30000`, and it seems to work.

Sorry about that.

**Comment by jesus-gorronogoitia** [comment]
Bonjour Benjamin, 
Merci for you advice. I will follow it and let you know.

**Comment by jesus-gorronogoitia** [comment]
I still get the TimeOutException, even with `--timeOut 120000 `
