### ISSUE TITLE
Problem following DSpot getting started in Windows 7

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#445]
#### Characteristics

- **Issue Type**:  possible bug

- **Reproducibility**:  always

- **Severity**:  block

- **Tool/Service/Component**:  DSpot

- **Execution Environment**:  Windows 7 Enterprise

- **Reporter**: Yosu Gorroñogoitia jesus.gorronogoitia@atos.net & Ricardo José Tejada ricardo-jose.tejadagarcia@atos.net

#### Description
Following the steps of DSpot getting started, several errors appear after mvn test in TestCompiler.
If mvn package is run it produces a build failure and the DSpot jar is not generated (see DSpotProblem.png).

#### Steps to reproduce
Follow the DSpot getting started instructions in Windows 7.

git clone https://github.com/STAMP-project/dspot.git
cd dspot/dspot
mvn compile
mvn test (error)
mvn package (error)

#### Other files and URLs
DSpotProblem.png
![dspotproblem](https://user-images.githubusercontent.com/36235771/40491416-7ccb08e0-5f5d-11e8-91e8-7fcdfc10baa2.png)

[mavenTestResults.txt](https://github.com/STAMP-project/dspot/files/2035703/mavenTestResults.txt)

**Comment by danglotb** [comment]
This issue is very old and I close it. However, we all know the fact that the test pass in some environment (my laptop / travis / jenkins), but not on all.
