### ISSUE TITLE
DSpot cannot be built from sources using Maven: Test failures

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#462]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: DSpot (latest pull form master branch)
- **Execution Environment**: Linux OpenSuse Tumbleweed
- **Reporter**: Jesús 

#### Description
DSpot cannot be built from master branch sources following instructions. When packaging test failures are reported and packaging is aborted.
`

#### Steps to reproduce
On a clean local DSpor Git repository, cloned from master branch in GitHub, do:
`mvn clean package`

> Results :
> 
> Tests in error: 
>   testMultipleClasses(eu.stamp_project.automaticbuilder.MavenAutomaticBuilderTest): java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
>   testSpecificClass(eu.stamp_project.automaticbuilder.MavenAutomaticBuilderTest): java.lang.RuntimeException: Maven build failed! Enable verbose mode for more information (--verbose)
> 
> Tests run: 128, Failures: 0, Errors: 2, Skipped: 5
> 

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

Could you please provide me the full trace of the execution of the maven goals?

Thank you.

**Comment by jesus-gorronogoitia** [comment]
Here you have:
[maven_dspot_build.txt](https://github.com/STAMP-project/dspot/files/2162301/maven_dspot_build.txt)
