### ISSUE TITLE
NPE: in eu.stamp_project.minimization.GeneralMinimizer when using MethodAdd:MethodAdd:StatementAdd in Dhell

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#463]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot, latest version compiled from sources
- **Execution Environment**: Linux Opensuse Tumbleweed
- **Reporter**: Jesús Gorroñogoitia<jesus.gorronogoitia@atos.net>

#### Description
DSpot triggers a NPE when executed over DHell test project with a StatementAdd mutator. When replacing the mutator with MethodAdd, it works well. Any combination of mutators that include StatementAdd triggers the same exception.
#### Steps to reproduce
In dhell folder, in CMI execute the following DSpot command:
`java -jar ../dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar  -p /home/yosu/Projects/STAMP/Git/dhell/dspot_properties_files/DSpotNewTestConf_dspot.properties  -a MethodAdd:StatementAdd -s JacocoCoverageSelector -i 1`

> Dspot triggers the following NPE:
> Exception in thread "main" java.lang.NullPointerException
> 	at eu.stamp_project.minimization.GeneralMinimizer.lambda$inlineLocalVariable$7(GeneralMinimizer.java:148)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at eu.stamp_project.minimization.GeneralMinimizer.inlineLocalVariable(GeneralMinimizer.java:150)
> 	at eu.stamp_project.minimization.GeneralMinimizer.minimize(GeneralMinimizer.java:37)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at eu.stamp_project.utils.AmplificationHelper.createAmplifiedTest(AmplificationHelper.java:112)
> 	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:180)
> 	at eu.stamp_project.dspot.DSpot.amplifyTest(DSpot.java:156)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:135)
> 	at eu.stamp_project.dspot.DSpot.amplifyAllTests(DSpot.java:117)
> 	at eu.stamp_project.Main.run(Main.java:68)
> 	at eu.stamp_project.Main.run(Main.java:91)
> 	at eu.stamp_project.Main.main(Main.java:42)

Using default dhell configuration for DSpot.

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

Thank for reporting this issue.

For now, please use `no-minimize` command line option to disable the minimization feature.

I'll have a look at it ASAP.

**Comment by jesus-gorronogoitia** [comment]
Merci Benjamin, when using --no-minimize flag, DSpot works well. Is it documented?

**Comment by danglotb** [comment]
Since the minimization has been disabled in DSpot, I'm closing this issue. You may reopen it if you encounter any trouble when the minimization will work again.
