### ISSUE TITLE
Create a Jenkins plugin to automatically or pipeline script to call DSpot on the diff from a commit

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#468]
Use case I'd like to implement on XWiki:
* 1) a dev commits code
* 2) an xwiki ci job is triggered and inside this job DSpot is called with the diff info from the commit
* 3) the pipeline script commits the generated new tests in XWiki's SCM
* 4) XWiki's Maven build is modified so that amplified tests are executed as part of Xwiki's build as standard junit tests

On the XWiki side, we can implement 3) and 4) but we need someone to implement the step 2), i.e. integrate Dspot and Jenkins for commit diffs.

**Comment by bbaudry** [comment]
@nicolabertazzo , @danzone : can ENG handle step 2?

**Comment by danglotb** [comment]
Hi,

> an xwiki ci job is triggered and inside this job DSpot is called with the diff info from the commit

I developed a mode for **DSpot** that select test classes and test methods to be amplified according to a diff: see [this](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/eu/stamp_project/diff/SelectorOnDiff.java#L40)

However, this algorithm is not (yet) tested and required to have the commit sha in the properties file, see the [documentation](https://github.com/STAMP-project/dspot#selector-on-diff-from-github).

Thus, the selection of the tests may be flawed for now.

**Comment by spookyvale** [comment]
I just started working on a first version of a jenkins plugin for Dspot, so it can be added as a separate build step (trying to ensure pipeline support as well).
I will investigate the possibility to run on diffs only.

**Comment by monperrus** [comment]
Dspot is able to work on a diff. @danglotb where is the documentation for this?

**Comment by danglotb** [comment]
I'm merging `diff-test-selection repository` in this one, to make this maven plugin a module of DSpot, see PR #680.

There is some documentation available in the README on why it works and an execution's example in the travis' scripts.

I'm gonna make the documentation clearer and add a part on the integration with DSpot and DSpot-maven.

**Comment by danglotb** [comment]
I'm closing this issue since there is a dedicated repository for this.
