### ISSUE TITLE
dspot snapshot repo not being updated

### ISSUE THREAD

**Issue by spookyvale** [STAMP-project/dspot#486]
I just wanted to notify that latest builds have not been released to the OSS snapshot repo (since July 18). 
I do not know if this is the intended behavior. 
It was quite useful to test the latest version of dspot with the integration tools being developed...

**Comment by danglotb** [comment]
Hi, thank you for reporting this issue. 
According to the log on travis, there is an issue with the path to the script that deploys the snapshot.
I'm gonna fix it.

**Comment by spookyvale** [comment]
both DSpot and testrunner are not being updated. In deploy script I see the repo returns 401 - unauthorized.
I don't have means to check the account myself, sorry.

**Comment by danglotb** [comment]
Hi, my credentials have been comprised. I updated stamp artifacts settings. Thank you and sorry.
