### ISSUE TITLE
feature: add support for junit rule annotations

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#50]
Motivation: Some Junit tests use the [@Rule](http://junit.org/junit4/javadoc/4.12/org/junit/Rule.html), which result in specific setups. Currently, DSpot does not support those tests. 

Output: A pull request on Dspot with tests showing that DSpot is able to amplify tests with @Rule.

**Comment by monperrus** [comment]
This works with the standard Junit runner.
