### ISSUE TITLE
Dspot is hung on xwiki-commons-cache-infinispan

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#532]
In the past I was able to run dspot on xwiki-commons/xwiki-commons-core/xwiki-commons-cache/xwiki-commons-cache-infinispan (see https://massol.myxwiki.org/xwiki/bin/view/Blog/TestGenerationDspot). It just wasn't generating any new tests. But today I build dspot from sources and it's hanging:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.228 s
[INFO] Finished at: 2018-09-04T12:02:37+02:00
[INFO] Final Memory: 46M/843M
[INFO] ------------------------------------------------------------------------
[INFO] 2018-09-04 12:02:38 MavenAutomaticBuilder - run maven org.pitest:pitest-maven:1.4.0:mutationCoverage -DwithHistory -DtargetClasses=org.xwiki.* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/ 
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
```

dspot.properties:

```
project=../../../
targetModule=xwiki-commons-core/xwiki-commons-cache/xwiki-commons-cache-infinispan
src=src/main/java/
testSrc=src/test/java/
testResources=src/test/resources/
javaVersion=8
outputDirectory=output
filter=org.xwiki.*
srcResources=src/main/resources/
#excludedClasses=org.xwiki.job.internal.xstream.SafeXStreamTest,org.xwiki.job.internal.DefaultJobStatusStoreTest
```

**Comment by vmassol** [comment]
or maybe I didn't leave it running long enough? I let it run about 3-4 minutes

**Comment by danglotb** [comment]
Hi @vmassol 

I think **DSpot** is running the original mutation analysis with pit (see `[INFO] 2018-09-04 12:02:38 MavenAutomaticBuilder - run maven org.pitest:pitest-maven:1.4.0:mutationCoverage -DwithHistory -DtargetClasses=org.xwiki.* -DreportsDirectory=target/pit-reports -DoutputFormats=CSV,HTML -DtimeoutConst=10000 -DjvmArgs=16G -DmutationEngines=gregor -Dmutators=ALL -DadditionalClasspathElements=target/dspot/dependencies/ 
`) and it takes some time.

If you want to have some logs about it, you can enable the verbose mode with `--verbose` flag on the command line.

Thank you.

**Comment by vmassol** [comment]
Indeed you're right, it was not hanging, just slow...
