### ISSUE TITLE
DSpot should not remove Assert.fail() in existing try/catch block

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#533]
Before generating assertions, **DSpot** removes all the assertions but should not remove `Assert.faill()` in existing try/catch block.

**Comment by danglotb** [comment]
I'm asking myself if **DSpot** should remove the `try/catch block` and the `Assert.fail()` statement because it will regenerate it if the given test still sets the program into an "incorrect" state.

Perhaps, it will allow to derive from a test with `try/catch block` and the `Assert.fail()`  a test that does no set the program into an "incorrect" state.

**Comment by monperrus** [comment]
I don't really understand. When are those Assert.fail() removed?
