### ISSUE TITLE
Use static imports in generated/modified test classes

### ISSUE THREAD

**Issue by fduminy** [STAMP-project/dspot#568]
In my case, the generator has remove all my ```import static``` in a modified test class.

original/added methods contains now things like Mockito.when and ArgumentMatchers.argThat, which I don't want to have. That's same for non-test-related static imports.

The source code generator/modifier should use ```import static``` as much as possible, and add ones if necessary.

**Comment by danglotb** [comment]
Hi @fduminy 

This issue is more related to [Spoon](https://github.com/INRIA/spoon), the dependency that builds, analyze, transforms and print out the java model.

I'll look further on this.
