### ISSUE TITLE
Date issue with auto committing DSpot generated tests

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#579]
I just want to raise a use case. On the XWiki project we've been wanting to use the following strategy for DSpot:
* Have a jenkins pipeline job that would execute either regularly or whenever there's a commit and run Dspot, and commit the generated tests in the source tree.

Today, we've just found a DSpot-generated test that would lead to a "flicker" if this strategy was followed: the original test was comparing the received values with today-1day and today+1day and dspot tough it would put a more exact validation and used today's date! Thus the test would pass today and fail tomorrow.

One idea would be to be able to configure DSpot to tell it to not mutate Date objects. 

WDYT?

**Comment by danglotb** [comment]
> One idea would be to be able to configure DSpot to tell it to not mutate Date objects.

What do you mean by "mutate"?

> Thus the test would pass today and fail tomorrow.

You mean that **DSpot** generated assertions based on an object that represents the current date?

If so, it is an issue in fact. 

We have to implement a blacklist on objects to avoid such assertions and assertions based on others problematic value, such as absolute paths.

**Comment by vmassol** [comment]
> What do you mean by "mutate"?

I haven't seen the test since it's Thomas who did it but he told me that the new generated test had some comparison with today's date hardcoded.

**Comment by tmortagne** [comment]
> You mean that DSpot generated assertions based on an object that represents the current date?

See https://github.com/STAMP-project/dspot-usecases-output/blob/master/xwiki/2018-10-16-commons-crypto-pkix/org/xwiki/crypto/pkix/internal/BcX509CertificateGeneratorFactoryTest.java#L199.

The test is validating the certificate date using assertEquals for each getMonth, getHours, etc. of the date which does not work for a very long time :)

**Comment by vmassol** [comment]
Retested with PIT/Descartes and got 0 new tests while we had 2 with PIT/Gregor. So far all my tests with PIT/Descartes yielded 0 tests, I think there might be a problem.
