### ISSUE TITLE
Generated tests with jacoco selector doesn't compile

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#586]
command line: `java -jar /Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --test-criterion JacocoCoverageSelector --verbose --generate-new-test-class --with-comment`

Executed in `xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default`

Generates a AmplEmbeddableComponentManagerTest test case class which has:

```
...
    @Test(timeout = 10000)
    public void testLookupThisComponentManager() throws Exception, ComponentLookupException {
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getParent());
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getNamespace());
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getComponentEventManager());
        // AssertGenerator create local variable with return value of invocation
        Object o_testLookupThisComponentManager__3 = new EmbeddableComponentManager().getInstance(ComponentManager.class);
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (o_testLookupThisComponentManager__3)).getParent());
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (o_testLookupThisComponentManager__3)).getNamespace());
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (o_testLookupThisComponentManager__3)).getComponentEventManager());
    }
...
```

And this doesn't compile (variable "ecm" isn't declared...).

<img width="1005" alt="screen shot 2018-10-17 at 16 52 30" src="https://user-images.githubusercontent.com/628267/47095189-10156900-d22d-11e8-9394-5ee0b46c2d64.png">

**Comment by vmassol** [comment]
Missing `EmbeddableComponentManager ecm = new EmbeddableComponentManager();`.

**Comment by vmassol** [comment]
Original test:

```
    @Test
    public void testLookupThisComponentManager() throws ComponentLookupException
    {
        EmbeddableComponentManager ecm = new EmbeddableComponentManager();

        Assert.assertSame(ecm.getInstance(ComponentManager.class), ecm);
    }
```

**Comment by vmassol** [comment]
Seems like a pretty important bug.

Also I don't understand how DSpot could have executed this test... It should have failed

**Comment by vmassol** [comment]
And there are other compile errors such as:

```
    @Test(timeout = 10000)
    public void testComponentDescriptorInjection() throws Exception {
        EmbeddableComponentManager ecm = new EmbeddableComponentManager();
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getParent());
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getNamespace());
        // AssertGenerator add assertion
        Assert.assertNull(((EmbeddableComponentManager) (ecm)).getComponentEventManager());
        DefaultComponentDescriptor<AmplEmbeddableComponentManagerTest.Role> d = new DefaultComponentDescriptor<>();
        d.setRoleType(AmplEmbeddableComponentManagerTest.Role.class);
        d.setImplementation(AmplEmbeddableComponentManagerTest.ComponentDescriptorRoleImpl.class);
        DefaultComponentDependency dependencyDescriptor = new DefaultComponentDependency();
        dependencyDescriptor.setRoleType(new DefaultParameterizedType(null, ComponentDescriptor.class, AmplEmbeddableComponentManagerTest.ComponentDescriptorRoleImpl.class));
        dependencyDescriptor.setName("descriptor");
        d.addComponentDependency(dependencyDescriptor);
        ecm.registerComponent(d);
        // AssertGenerator add assertion
        Assert.assertFalse(((ComponentDescriptor) (((AmplEmbeddableComponentManagerTest.ComponentDescriptorRoleImpl) (impl)).getComponentDescriptor())).getComponentDependencies().isEmpty());
        // AssertGenerator add assertion
        Assert.assertEquals("org.xwiki.component.embed.AmplEmbeddableComponentManagerTest$Role", ((Type) (((ComponentDescriptor) (((AmplEmbeddableComponentManagerTest.ComponentDescriptorRoleImpl) (impl)).getComponentDescriptor())).getRoleType())).getTypeName());
        // AssertGenerator add assertion
        Assert.assertEquals("default", ((ComponentDescriptor) (((AmplEmbeddableComponentManagerTest.ComponentDescriptorRoleImpl) (impl)).getComponentDescriptor())).getRoleHint());
        ecm.getInstance(AmplEmbeddableComponentManagerTest.Role.class).getComponentDescriptor();
    }
```

"impl" and "ecm.getInstance(AmplEmbeddableComponentManagerTest.Role.class).getComponentDescriptor();" are not compiling

**Comment by danglotb** [comment]
The error come from the minimization of **DSpot**, which aims at reducing the number of statements by removing statements judged useless.

I'm gonna disabled it. I think it is not necessary for now.

**Comment by danglotb** [comment]
#590 should fix the compilation problems. 

After the merge, please pull and retry.

If you are still in trouble, please update me.

@assadOW2 You should also pull and retry, see if your compilation problems are removed.

**Comment by vmassol** [comment]
It fixes the problem since now with PIT/Descartes I don't get any tests generated at all ;)

**Comment by danglotb** [comment]
> It fixes the problem since now with PIT/Descartes I don't get any tests generated at all ;)

But in this issue, you used `JacocoCoverageSelector`, isn't? 

Did you run DSpot with the `PitMutantScoreSelector` before the fix and got some amplified test methods, and now you don't?

**Comment by assadOW2** [comment]
@danglotb : I pulled the last version but have build issues, tests don't pass. So for now I am skipping them as you advised me.

**Comment by assadOW2** [comment]
@danglotb : regarding compilation problems, I still have some. 

For instance, this kind of line : 
        int o_test__1 = this.optimizer.newVar(4);

produces this kind of error:

[ERROR] /home/assadm/OW2-Projects/Forks/sat4j/org.sat4j.core/src/test/java/org/sat4j/minisat/core/TestPrimeComputation.java:[25,29] cannot find symbol
[ERROR] symbol: variable optimizer

**Comment by danglotb** [comment]
Hi @assadOW2 

Could you please, provide me more information?

You are amplifying the core module of sat4j, right? Could please give the command line and the property file used?

**Comment by assadOW2** [comment]
Hi @danglotb 

Yes of course. I am indeed amplifying the core module of sat4j, in attachment the property file and here is the command line that generates my new tests:
~/OW2-Projects/Forks/sat4j$ java -jar  /home/assadm/STAMP-project/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties

The jar is the one generated from latest source on the repository. Once the files generated, I replace existing test suite files with the one generated with DSpot. Then I run mvn test on my project. 
[dspot.txt](https://github.com/STAMP-project/dspot/files/2500493/dspot.txt)

**Comment by assadOW2** [comment]
Hi @danglotb

Yes of course. I am indeed amplifying the core module of sat4j, in attachment the property file and here is the command line that generates my new tests:
~/OW2-Projects/Forks/sat4j$ java -jar /home/assadm/STAMP-project/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties

The jar is the one generated from latest source on the repository. Once the files generated, I replace existing test suite files with the one generated with DSpot. Then I run mvn test on my project.

[dspot.txt](https://github.com/STAMP-project/dspot/files/2500506/dspot.txt)

**Comment by assadOW2** [comment]
Hi @danglotb

Yes of course. I am indeed amplifying the core module of sat4j, in
[dspot.txt](https://github.com/STAMP-project/dspot/files/2500523/dspot.txt)
 attachment the property file and here is the command line that generates my new tests:
~/OW2-Projects/Forks/sat4j$ java -jar /home/assadm/STAMP-project/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties

The jar is the one generated from latest source on the repository. Once the files generated, I replace existing test suite files with the one generated with DSpot. Then I run mvn test on my project.

**Comment by danglotb** [comment]
Hello @assadOW2 

Please refer to #600 for your issue. 

I'm closing this one.
