### ISSUE TITLE
Clover selector doesn't generate any test for xwiki-commons-component-default

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#588]
I tried the clove selector on `xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default` with `java -jar /Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --test-criterion CloverCoverageSelector --verbose --generate-new-test-class --with-comment` and was surprised that it didn't generate any test. Especially since when executed with the jacoco selector it does generate new tests (19 new tests to be precise).

I understand that the clover selector increases branch coverage while the jacoco one increases instruction coverage. Is that the reason or is there another problem?

I'm attaching the output dir.

[output.zip](https://github.com/STAMP-project/dspot/files/2488346/output.zip)

**Comment by danglotb** [comment]
> I understand that the clover selector increases branch coverage while the jacoco one increases instruction coverage. Is that the reason or is there another problem?

Yes, it might be the explanation but it can be also a bug in the CloverSelector.

**Comment by danglotb** [comment]
I close this issue since the CloverSelector has been disabled.
