### ISSUE TITLE
Error building latest DSpot

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/dspot#592]
#### Characteristics
- **Issue Type**: building
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: DSpot
- **Execution Environment**: Windows 10, Maven
- **Reporter**: Lars Thomas Boye

#### Description
Pulling the latest and trying to build with mvn compile today, it fails to resolve one dependency. This used to work. I would like to be able to build, to try to modify DSpot to work on Windows.

Error:
Failed to execute goal on project dspot: Could not resolve dependencies for project eu.stamp-project:dspot:jar:1.1.1-SNAPSHOT: Could not find artifact org.benf:cfr:jar:0.132.0 in central (http://artifactory.tellucloud.com/artifactory/libs-release)

**Comment by danglotb** [comment]
This artifact comes from jdt, a dependency of Spoon.

Sometimes such dependencies are down for a time. 

Could you retry in a while?

**Comment by danglotb** [comment]
Hi @ltboye 

I look up to find a solution to this problem, but I don't know how to fix this.

We can try a manual things: I provide you manually the missing jar, `org.benf:cfr:jar:0.132.0` and retry.

WDYT?

**Comment by ltboye** [comment]
Yes, let's do that. And I'll report if there are any more missing dependencies.

**Comment by danglotb** [comment]
Please find it in [benf.zip](https://github.com/STAMP-project/dspot/files/2514276/benf.zip), it contains the missing dependency from my own local maven repository.

You should put its content in `<path-to-your-local-maven-repo>/.m2/repository/org/`

**Comment by ltboye** [comment]
Trying on my home machine (also Win10), it builds successfully (skipping tests).

I will try on the office machine again tomorrow.

**Comment by ltboye** [comment]
I still get the same error on my office machine, even though I have tried with and without Maven config file, removed the files in question from the local artifactory, etc. My laptop has the same problem. My home computer works.

The only difference I can think of right now is that the Maven and Java installs on my home machine is older (but should be compatible). Maven on my office machine is 3.5.4.

Now I can use the released jar instead of building myself, but that also still fails to work on my office machine!

**Comment by danglotb** [comment]
Closing this issue. Please reopen it or open a new one. Thank you.
