### ISSUE TITLE
FEAT: Don't break DSpot execution on failures on one concrete test case under amplification. Move to another one if possible

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#606]
#### Characteristics
- **Issue Type**: feature
- **Reproducibility**: always,
- **Severity**: feature
- **Tool/Service/Component**: DSpot
- **Execution Environment**: All supported
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
When DSpot has been used to amplify the test coverage of Supersede IF component, it was not way to run DSpot on the complete IF test base, despite this test was green, because of different issues. Therefore, the strategy was to run DSpot on individual test cases, getting DSpot to complete the task for some cases and not (based on reported issues) for others.
Therefore, I wonder if DSpot can manage the work over the different test cases in a way that, provide the complete test cases are green (as reported by mvn test), it can go through them in sequence, breaking and moving to next test case in case that any exception triggers, but not breaking the complete execution. Upon the occurrence of any issue, it can be reported to the users. At the end of the execution, DSpot can report the test cases that were successfully amplified and those for whom it fails to complete the amplification. 

#### Steps to reproduce
N/A
#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Working on this see #625

**Comment by danglotb** [comment]
#625 has been merged. I'm closing this one.
