### ISSUE TITLE
Dspot keeps existing tests with --generate-new-test-class

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/dspot#612]
I ran `java -jar /Users/vmassol/dev/dspot/dspot/target/dspot-1.1.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties --descartes --verbose --generate-new-test-class --with-comment --amplifiers StringLiteralAmplifier:NumberLiteralAmplifier:CharLiteralAmplifier:BooleanLiteralAmplifier:AllLiteralAmplifiers:MethodAdd:MethodRemove:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifie` on `xwiki-commons/xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-api` and got some generated classes with test already existing.

For example:

```
public class AmplNamespaceUtilsTest {
    @Test
    public void getPrefix() {
        Assertions.assertNull(NamespaceUtils.getPrefix(null));
        Assertions.assertNull(NamespaceUtils.getPrefix("namespace"));
        Assertions.assertEquals("type", NamespaceUtils.getPrefix("type:value"));
        Assertions.assertEquals("t:pe", NamespaceUtils.getPrefix("t\\:pe:value"));
        Assertions.assertEquals("", NamespaceUtils.getPrefix(":value"));
    }
...
```

which already exists in `NamespaceUtilsTest`:

```
public class NamespaceUtilsTest
{
    @Test
    public void getPrefix()
    {
        assertNull(NamespaceUtils.getPrefix(null));
        assertNull(NamespaceUtils.getPrefix("namespace"));
        assertEquals("type", NamespaceUtils.getPrefix("type:value"));
        assertEquals("t:pe", NamespaceUtils.getPrefix("t\\:pe:value"));
        assertEquals("", NamespaceUtils.getPrefix(":value"));
    }
...
```

Thanks

**Comment by vmassol** [comment]
Note: I built dspot from sources today around 12:00 CEST.

**Comment by vmassol** [comment]
On a different but related topic, I got 6+3+4 new tests generated with the amplifiers mentioned above which seems good. I now need to analyze the generated tests.

**Comment by danglotb** [comment]
Hi @vmassol 

There is an issue with this module. I don't know why, but I cannot compute original the mutation score. Each time I run pit on the module, it found 0 test.

When I run
```sh
mvn org.pitest:pitest-maven:1.4.0:mutationCoverage -DtargetClasses="org.xwiki.component*" -DtargetTests="org.xwiki.component*"
```
Outside DSpot, I obtain the traces:

```
12:47:18 PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
12:47:18 PIT >> INFO : Sending 34 test classes to minion
12:47:18 PIT >> INFO : Sent tests to minion
12:47:18 PIT >> INFO : MINION : 12:47:18 PIT >> INFO : Checking environment

12:47:19 PIT >> INFO : MINION : 12:47:19 PIT >> INFO : Found  0 tests

12:47:19 PIT >> INFO : MINION : 12:47:19 PIT >> INFO : Dependency analysis reduced number of potential tests by 0

12:47:19 PIT >> INFO : MINION : 12:47:19 PIT >> INFO : 0 tests received

12:47:19 PIT >> INFO : Calculated coverage in 0 seconds.
12:47:19 PIT >> INFO : Created  12 mutation test units
12:47:19 PIT >> INFO : Completed in 1 seconds
```

Did you manage to execute correctly PIT on this module?

**Comment by vmassol** [comment]
> Did you manage to execute correctly PIT on this module?

Yes, I did, see https://github.com/STAMP-project/dspot/issues/612#issuecomment-433001508

**Comment by danglotb** [comment]
These tests are JUnit5.

I think that is why. It seems that to run pit on JUnit5, we need to use a plugin: `https://repo.maven.apache.org/maven2/org/pitest/pitest-junit5-plugin/0.5/pitest-junit5-plugin-0.5.pom`

I plan to work on the support of JUnit5 but I am afrait that your current result are flawed.

**Comment by vmassol** [comment]
@danglotb Good point. Some questions:

1) I don't see what this has to do with this issue which is about not keeping old tests, could you explain?
2) Why is DSpot able to generate tests if it cannot notice existing tests?

**Comment by danglotb** [comment]
> I don't see what this has to do with this issue which is about not keeping old tests, could you explain?

Yes, there is no link with the issue sorry. The fact is #613 and this one is related to the amplification of the same module, _i.e._ `xwiki-commons-component-api`. I wanted to investigate both problems but I found the problem of pit and JUnit5.

> Why is DSpot able to generate tests if it cannot notice existing tests?

Because before the amplification, **DSpot** computes the baseline, _i.e._ the mutation score using the original test suite. For now, It uses the standard pit, and thus the JUnit5 tests are not used, which result with 0% of mutation score.
So, for the amplification, **DSpot** uses a baseline that have 0% of mutation score.
Then, it generates JUnit4 test methods, and **DSpot** is able to compute the mutation score of these and so, amplified test methods increase the mutation score, because the baseline is 0%.

**Comment by vmassol** [comment]
ok thanks for the explanation so what you're saying is that if the original mutation score was computed properly DSpot/Descartes would probably not have generated any new tests, right? :)

**Comment by danglotb** [comment]
> DSpot/Descartes would probably not have generated any new tests, right? :)

No, I did not say that.

**Comment by danglotb** [comment]
I thought about this issue of JUnit5.

You can workaround by first, run pit offline of **DSpot** and keep the csv mutations reports (you will have to enable the CSV format with `-DoutputFormats=CSV,HTML` (you will have both csv and html file).

In `target/pit-reports/YYYYMMDD/` you should find a `mutations.csv`.

Copy it into a specific place, let's say `<path/to/mutations.csv>`.

Then when running **DSpot**, use the option: `(-m|--path-pit-result) <./path/to/mutations.csv>`.

However, you must be aware of the mutators that you are using.

You can find the mutators operators used by **DSpot** [here](https://github.com/STAMP-project/dspot/blob/master/dspot/src/main/java/eu/stamp_project/mutant/pit/MavenPitCommandAndOptions.java#L47).

You can specify the list of mutators used by `descartes` with the property `descartesMutators`, _e.g._ `descartesMutators='A',void,null`.

By default, **DSpot** uses the default mutators of **Descartes**.

**Comment by danglotb** [comment]
To come back to the issue, It keeps the original tests because there are JUnit5. I'll propose a pull request ASAP.
