### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#617]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot, latest version compiled from source at 26/10
- **Execution Environment**: CentOS7
- **Reporter**: Jesús Gorroñogoitia<jesus.gorronogoitia@atos.net>
#### Description
DSpot gets the VM out of memory when executed within a collection of test cases reference by wildcard *:
`eu.supersede.integration.api.monitoring.proxies.test.*`

See [exception](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810261419/dspot.exception)

##### Properties file

See `[dspot.properties](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810261419/dspot.properties)`

##### Command Line / Options
`DSpot CLI configuration:  -i 3 -t eu.supersede.integration.api.monitoring.proxies.test.* -a AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier -s JacocoCoverageSelector --timeOut 30000 --max-test-amplified 200 --budgetizer NoBudgetizer --verbose
`

See execution [logs](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810261419/dspot.log)

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hi @jesus-gorronogoitia 

I know this is painful, but I don't have a magical solution. 

You can either supply more memory to your java process or amplify test class per test class, in the worst case test method per test method.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb don't worry, I am reporting these issues as part of our work as evaluators and issue reporters. As commented, I've already increased the memory with not sucess and I am now working on DSpot amplification per test class, which works.
Understanding that apart from these suggestions there is nothing else you can do, I close the issue
