### ISSUE TITLE
Latest release: mvn test stage failure on build 

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#623]
#### Characteristics
- **Issue Type**: [ test ]
- **Reproducibility**: [always]
- **Severity**: [minor]
- **Tool/Service/Component**: [name, version]
- **Execution Environment**: [ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org]

#### Description

Test stage fails:

"Tests in error: 
  DSpotUtilsTest.testGetAllTestClasses:39 » NullPointer"

Build ok when skipping tests. 

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Closing this issue. Please reopen it or open a new one. Thank you.
