### ISSUE TITLE
Main - Amplification failed

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#626]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot 1.2.1
- **Execution Environment**: CentOS7
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
DSpot executed on test: eu.supersede.integration.api.monitoring.proxies.test.DiskMonitorProxyTest of Supersede IF component ends normally without exceptions but reporting:
`2018-10-29 17:32:31 Main - Amplification failed.`

No additional information is provided by DSpot.

##### Properties file
See [dspot.properties](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810291732/dspot.properties)

##### Command Line / Options
DSpot CLI configuration:  `-i 3 -t eu.supersede.integration.api.monitoring.proxies.test.DiskMonitorProxyTest -a AllLiteralAmplifiers:MethodGeneratorAmplifier:ReturnValueAmplifier:NullifierAmplifier -s JacocoCoverageSelector --timeOut 30000 --max-test-amplified 200 --budgetizer NoBudgetizer --verbose`

Is this normal behavior?. Does it mean something (expected) happened so DSpot quit normally reporting only that the amplification failed? Shouldn't it report the reason it failed?

#### Other files and URLs
See execution [logs](https://github.com/STAMP-project/dspot-usecases-output/blob/master/atos/supersede/IF/DSpot/JacocoCoverageSelector/AllLiteralAmplifiers-MethodGeneratorAmplifier-ReturnValueAmplifier-NullifierAmplifier/201810291732/dspot.log).

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Closing this issue. Please reopen it or open a new one. Thank you.
