### ISSUE TITLE
Tellu test report/status

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/dspot#635]
#### Characteristics
- **Issue Type**: test report
- **Tool/Service/Component**: DSpot, built 01.11.2018
- **Execution Environment**: Windows 10
- **Reporter**: Lars Thomas Boye

#### Description
Having run a number of DSpot tests, I wanted to briefly sum up the findings so far. The complete test reports and outputs are found in the dspot-usecases-output repo, in the Tellu folder.

- DSpot only works on one of the three systems (all Win10) I have available, my home computer. Only difference I have found is that it has slightly older Java and Maven versions, though all are Java 8 and Maven 3.5.x, and with environment variables set in the same way.

- JacocoCoverageSelector does not work for me. It seems no coverage report is produced.

- Many test runs are ended with an IllegalArgumentException "character to be escaped is missing".

- Testing different amplifiers with the default selector, limiting amplification to a single test class, it still took very long to run, with the CPU mostly idle (I gave up on AllLiteralAmplifiers after five hours). Reducing timeOut to 1000 made the times feasible. Not many were able to run to completion, and those that did failed to generate any new tests.

To run more experiments I would need some input on what else to try with regards to configuring DSpot etc. (see test reports in dspot-usecases-output for what has already been tried).

**Comment by danglotb** [comment]
Hi @ltboye 

Thank you for reporting this.

It seems that DSpot does not support some system separator. I'm gonna investigate on it.

Could you please, push on the repository [STAMP-project/dspot-usecases-output/tree/master/Tellu](https://github.com/STAMP-project/dspot-usecases-output/tree/master/Tellu) the traces? 

 > To run more experiments I would need some input on what else to try with regards to configuring DSpot etc. (see test reports in dspot-usecases-output for what has already been tried).

I saw that you ran amplifiers one by one. What you can do, is to explore more by associating them, _e.g._ `--amplifiers MethodAdd;MethodGeneratorAmplifier;...`. You can mix them as you what (the order should not have any impact), separate each name with a `;` since you are running Windows. 

Best.

**Comment by ltboye** [comment]
Hi @danglotb 

All traces are in the repo. Here are some examples of the exception:
https://github.com/STAMP-project/dspot-usecases-output/blob/master/Tellu/TelluLib-2018-11-01/Run-filter.txt
https://github.com/STAMP-project/dspot-usecases-output/blob/master/Tellu/TelluLib-ModelTest-Descartes-Amplifiers/MethodGeneratorAmplifier.txt

**Comment by danglotb** [comment]
It looks like that the error is thrown by :+1: 
`final String pathname = directory.getAbsolutePath() + File.separator + type.getQualifiedName().replaceAll("\\.", File.separator)
                + ".java";`.

It seems that you have some test classes that have no packages (_i.e._ they are in default package).

I'll fix this ASAP and keep you update.

**Comment by danglotb** [comment]
> It seems that you have some test classes that have no packages (i.e. they are in default package).

This is not the issue. It seems that we need to escape the escape character for windows. However, I cannot test on my side... If you could pull and build #642 and retry to see if I did fix it or not.

**Comment by ltboye** [comment]
Yes, I will try the next time I have a chance to test on my home computer (still not building or running on the others).

**Comment by ltboye** [comment]
@danglotb 

I tried your fix. Unfortunately it did not fix the issue.

Experiments here:
https://github.com/STAMP-project/dspot-usecases-output/tree/master/Tellu/TelluLib-EscapeFix

**Comment by ltboye** [comment]
I have also been trying the JacocoCoverageSelector with this fixed version. It gives a different result than before, but still stops with an exception.

See https://github.com/STAMP-project/dspot-usecases-output/tree/master/Tellu/TelluLib-ModelTest-Jacoco

**Comment by danglotb** [comment]
Closing this issue. Please reopen it or open a new one. Thank you.
