### ISSUE TITLE
The Maven plugin generate duplicate <profiles> tag if one already exist

### ISSUE THREAD

**Issue by tmortagne** [STAMP-project/dspot#640]
Version: fcfbbe14b62f19b5fb5ab5eb43830cc135d819c6

I executed the following command on https://github.com/xwiki/xwiki-commons/tree/master/xwiki-commons-core/xwiki-commons-job:

```
mvn clean eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests -e -Dverbose=true -Dwith-comment=true -Damplifiers=BooleanLiteralAmplifier
```

and end up with the attached [.dspot_pom.xml](https://github.com/STAMP-project/dspot/files/2552998/dspot_pom.xml.zip).

Looks like the plugin add a new `<profiles>` without checking if there is already one or not.

**Comment by danglotb** [comment]
Hi @tmortagne 

Thank you for reporting this.

> Looks like the plugin add a new <profiles> without checking if there is already one or not.

We agree it should not.

**Comment by danglotb** [comment]
Should be fixed with #641

**Comment by tmortagne** [comment]
That was fast :)

**Comment by tmortagne** [comment]
Looks OK indeed.
