### ISSUE TITLE
OutOfMemoryError with the Maven plugin in some module

### ISSUE THREAD

**Issue by tmortagne** [STAMP-project/dspot#644]
#### Characteristics
- **Issue Type**: bug
- **Severity**: crash
- **Tool/Service/Component**: Maven plugin, 9dda0c3cca148bf772c265dedc16c7de70a3d91b
- **Execution Environment**: Ubuntu 18.10 64b, Java 1.8.0_191 with -Xmx1024m

#### Description

Getting a OutOfMemoryError after a while when executing `mvn clean eu.stamp-project:dspot-maven:1.2.2-SNAPSHOT:amplify-unit-tests -Dgenerate-new-test-class=true -Dwith-comment=true -Dclean=true -Ddescartes=true -e -Dwith-comment=true -Damplifiers=StringLiteralAmplifier` on module https://github.com/xwiki/xwiki-commons/tree/master/xwiki-commons-core/xwiki-commons-context.

The tests in that module don't use much memory and the fact that it happen after a while sounds like a memory leak or just that dspot store (directly or indirectly) way too much stuff in memory.

Here is the end of the log (not super useful but might give hints of what it was doing when it crashed):

```
[INFO] Assertion amplification: 200 test method(s) has been successfully amplified.
[INFO] Using /DATA/projets/xwiki/src/git/xwiki-commons/xwiki-commons-core/xwiki-commons-context/.dspot_pom.xml to run maven.
[INFO] Using /home/tuska/utils/mvn for maven home
[INFO] run maven: /home/tuska/utils/mvn/bin/mvn org.pitest:pitest-maven:mutationCoverage -DtargetTests=org.xwiki.context.internal.concurrent.DefaultContextStoreManagerTest
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
[INFO] 34 mutants has been generated (34)
[INFO] 0 amplified test methods has been selected to be kept.
[INFO] iteration 1 / 3
[INFO] 200 tests selected to be amplified over 200 available tests
[INFO] Amplification of inputs...
  5% |================================= ]-[WARNING] Something bad happened during input amplification.
 36% |================================= ]|[INFO] 0 amplified test methods has been selected to be kept. (global: 0)
[INFO] elapsedTime 107786
 58% |================================================= ]|[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:14 min
 94% |================================================= ]|[INFO] Finished at: 2018-11-06T16:40:42+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] GC overhead limit exceeded -> [Help 1]
java.lang.OutOfMemoryError: GC overhead limit exceeded
 89% |================================================= ]\[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
 86% |================================================= ]|
```

**Comment by danglotb** [comment]
Hi,
Thank you for reporting this.

The memory issue of DSpot is well known and I am sorry about it.

Here are some workarounds: 

1. Increase the memory with `-Xms -Xmx` options.
2. Amplify test class per test class.

I see that you use the `StringLiteralAmplifier`. If you have a test case that have a lot of different, the amount of potential amplified tests can be large, and thus consume a lot of memory. 

You can also experience with another input amplifier.

I am sorry but I do not have any magical fix for this.
