### ISSUE TITLE
Decrease in code coverage on Sat4j 

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#650]
#### Characteristics
- **Issue Type**: [test report]
- **Execution Environment**: [Ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org]

#### Description

Jacoco report shows a decrease in code coverage after adding (not replacing) 2 generated tests: https://github.com/STAMP-project/dspot-usecases-output/tree/master/OW2/Sat4j/20181102-0930/dspot-out/org/sat4j

Initial code coverage is: 21,901 of 43,508
New code coverage: 21,899 of 43,479

This is totally strange and I can't explain how adding new tests can reduce code coverage. 

##### Properties file

```java
project=.
src=src/main/java/
testSrc=src/test/java/
```

##### Command Line / Options

```shell
java -jar target/dspot-USED-VERSION-jar-with-dependencies.jar \
-p myPropertiesFile.properties
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @assadOW2 

I reproduced the problem. I used SAT4J with the following commit: `ec652dcd90e7277ff373ad073bed9fffa556d867`.

I ran: `mvn clean test jacoco:report` with a clean repository.

Then, I copy and paste both amplified test classes: `src/test/java/org/sat4j/AmplBugSAT107.java`, `src/test/java/org/sat4j/AmplBugSAT81.java` into the test suite and re-ran the same maven command line: `mvn clean test jacoco:report`.

In fact, I obtain a similar result, _i.e._ 21,902 of 43,508 w/o amplification and 21,901 of 43,508 with.

However, If we look closer, this number is the number of **MISSED** instructions, and thus, the less we miss instructions, the more we cover them, the better the test suite is.

I looked into the concerned package, _i.e._ `org.sat4j.minisat.restarts` (on my side), and we can observe the following result:

For the element `Restarts`: 
 * Before: 60% Cov., 4 Lines missed / 10
 * After: 66% Cov, 3 Lines missed / 10

I hope this answer to your issue.

I consider this issues as invalid for now, yet If you do encounter troubles, please, reopen-it or open a new one.

Best.
