### ISSUE TITLE
Translator exception on Seedstack core module

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/dspot#672]
#### Characteristics
- **Issue Type**: [test report]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Execution Environment**: [Ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org]

#### Description

Project Seedstack, module core: https://github.com/seedstack/seed

When executing DSpot I have this exception:
** ERROR eu.stamp_project.dspot.assertgenerator.Translator - Could not find getHost in com.google.common.net.HostAndPort**

#### Steps to reproduce

I built latest version of DSpot. I use Java 11 on Seedstack as it is required by Maven on this project.
```shell
export JAVA_HOME=/usr/lib/jvm/jdk-11.0.1
```

##### Properties file

```
project=.
targetModule=core
filter=org.seedstack.seed.core.*
src=src/main/java/
testSrc=src/test/java
javaVersion=11
outputDirectory=dspot-out/
timeoutConstInMillis=10000
jvmArgs=-Xmx2048m,-Xms1024m
excludedClasses=org.seedstack.seed.core.internal.crypto.EncryptionServiceBindingFactoryTest,org.seedstack.seed.core.internal.init.ProxyManagerTest,org.seedstack.seed.core.ValidationIT,org.seedstack.seed.core.internal.crypto.KeyPairConfigFactoryTest,org.seedstack.seed.core.KeyStoreIT,org.seedstack.seed.core.JndiIT,org.seedstack.seed.core.IgnoreIT,org.seedstack.seed.core.ExpressionLanguageIT,org.seedstack.seed.core.ExpressionLanguageHandlerIT,org.seedstack.seed.core.DiagnosticManagerIT,org.seedstack.seed.core.CryptoIT,org.seedstack.seed.core.CorePluginIT,org.seedstack.seed.core.ConfigurationProfilesIT,org.seedstack.seed.core.ConfigurationIT,org.seedstack.seed.core.CommandIT,org.seedstack.seed.core.CliIT
```
Those excluded classes are the ones I had to remove for Descartes because for an unknown reason Pit doesn't want to run on those ones. See this issue: https://github.com/STAMP-project/pitest-descartes/issues/93

##### Command Line / Options

```shell
java -jar  /home/assadm/STAMP-project/dspot/dspot/target/dspot-1.2.1-SNAPSHOT-jar-with-dependencies.jar --path-to-properties dspot.properties
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
This error has been fixed in 33aba8e4f2724cfe6082a6555012b6c228b06adc.

I plan to release soon DSpot.
