### ISSUE TITLE
Mistake in DSpot documentation

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#695]
Good afternoon :

In section "Maven plugin usage" the parameters are
written, -Dpath-to-properties dspot.properties.

But it is -Dpath-to-properties=dspot.properties,
using = instead of space.

Kind Regards.

**Comment by monperrus** [comment]
Good point! Could you please do a pull-request to fix it?

**Comment by jesus-gorronogoitia** [comment]
I will take care of updating the documentation in a pull request.

**Comment by jesus-gorronogoitia** [comment]
Pull request #696 created

**Comment by danglotb** [comment]
Close with #696.
