### ISSUE TITLE
jacoco 0.8.2 required for OpenJdk 10.0.2 (mvn test fails with jacoco 0.7)

### ISSUE THREAD

**Issue by gibello** [STAMP-project/dspot#705]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: dspot "mvn test"
- **Execution Environment**: JDK (OpenJDK 10.0.2) on ubuntu Linux 18.04
- **Reporter**: Pierre-Yves Gibello pyg@ow2.org

#### Description

mvn compile runs fine.
mvn test fails.

In the stack trace:
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.lang.Class.getField(Class.java:1690)

Changing the pom.xml in dspot/ solves the issue: replace 0.7.9 with 0.8.2 in <version> for jacoco and jacoco-maven-plugin .

#### Steps to reproduce

Just OpenJdk 10.0.2...

**Comment by danglotb** [comment]
#707  should fix this, thank you.

However, I'm afraid that we are far away from the support of Java 10.

**Comment by gibello** [comment]
Ok, back to java 8 (Oracle, hope it fits) and Jacoco 0.7.9, less risky - otherwise I'm afrait to add unexpectable problems ;)
