### ISSUE TITLE
OpenJdk 10.0.2 version not recognized causes test failure

### ISSUE THREAD

**Issue by gibello** [STAMP-project/dspot#706]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: mvn test on dspot
- **Execution Environment**: OpenJdk 10.0.2 on Ubuntu linux 18.04
- **Reporter**: Pierre-Yves Gibello pyg@ow2.org

#### Description

Test runPit_whenNoTestClassIsSpecified fails with error message "Could not determine java version from '10.0.2'" .

Results :

Failed tests:   runPit_whenAllDescartesMutatorsAreSpecified(eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilderWithDescartesTest): PIT results shouldn't be empty

Tests in error: 
  runPit_whenNoTestClassIsSpecified(eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilderTest): Could not determine java version from '10.0.2'.
  buildClasspath_whenAppliedToDSpotTestExampleProject(eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilderTest): Could not determine java version from '10.0.2'.
  compile_whenCleanCompileTestTasksAreAppliedToDSpotTestExampleProject(eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilderTest): Could not determine java version from '10.0.2'.
  runPit_whenTestClassIsSpecified(eu.stamp_project.automaticbuilder.gradle.GradleAutomaticBuilderTest): Could not determine java version from '10.0.2'.

#### Steps to reproduce

mvn test (using OpenJdk 10.0.2)

**Comment by danglotb** [comment]
Hello, and thank you for reporting this. 

I'm afraid that PIT does not support Java 10 yet. I'll have a look.
