### ISSUE TITLE
Maven plugin and DSpot output directory

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#712]
Good afternoon : 

Is the property outputDirectory supported by DSpot-Maven plugin ?
it is not working for me.

Thank you.

**Comment by danglotb** [comment]
Hello @RicardoTej 

In fact, the property `outputDirectory` (in the properties file specified by the CLI `--path-to-properties`) is automatically overridden by the default value of the parameter `-Douput-path`, _i.e._ `target/dspot/output`).

I opened #713 to fix it. Thank you!

**Comment by danglotb** [comment]
Fixed with #713
