### ISSUE TITLE
Documentation: refactor README to push forward usage instead of development.

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#716]
Hello all,

I propose to refactor the README, to make it user-oriented instead of developer-oriented. 

I know that we discuss a year ago about this, and we agreed to make it developer-oriented. But, people are always trying DSpot by building sources and I think they should pull the latest release or use the maven plugin before playing with the sources.

WDYT?

**Comment by monperrus** [comment]
OK for me. And we can move the appropriate content into README-developer.md.

**Comment by gibello** [comment]
Fine. A lot of interesting things already present in dspot-hands-on project concerning possible user doc... Maybe projects should be merged, or at least a link with explanations could be added somewhere ?

**Comment by danglotb** [comment]
Closed	danglotb opened this issue on 13 Sep 2018 · 0 comments
