### ISSUE TITLE
New rubbish files created in user directory during DSpot execution.

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#732]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: Dspot (latest version pulled/compiled from GitHub)
- **Execution Environment**: Linux Tumbleweed
- **Reporter**: Jesús Gorroñogoitia<jesus.gorronogoitia@atos.net>

#### Description
After last DSpot update, a  number of apparently random rubbish files are created in DSpot user directory (execution directory). Some files have .traces extension, others *.trces, *.trRaces, others are random names.
Examples:
```
-rw-r--r-- 1 yosu users         43 mar 11 12:32  foo2.traces
-rw-r--r-- 1 yosu users      33809 mar 11 12:32  NUL
-rw-r--r-- 1 yosu users         43 mar 11 12:32  :
-rw-r--r-- 1 yosu users         43 mar 11 12:32 ''$'\n'
-rw-r--r-- 1 yosu users         43 mar 11 12:32  my_storage.txt
-rw-r--r-- 1 yosu users         43 mar 11 12:32 'w:(:t7.L%A('
-rw-r--r-- 1 yosu users         43 mar 11 12:32  fo7o2.traces
-rw-r--r-- 1 yosu users         43 mar 11 12:32  foo2.trces
-rw-r--r-- 1 yosu users         43 mar 11 12:32  foo2Ktraces
-rw-r--r-- 1 yosu users         43 mar 11 12:32  hello_run3.traces
drwxr-xr-x 6 yosu users         74 mar 11 12:31  target/
-rw-r--r-- 1 yosu users          8 mar 11 12:31 'App should return some info'
-rw-r--r-- 1 yosu users          8 mar 11 12:31 'f o2.traces'
-rw-r--r-- 1 yosu users          8 mar 11 12:31 'foo2.t$races'
-rw-r--r-- 1 yosu users          8 mar 11 12:31  foo2.taces
-rw-r--r-- 1 yosu users          8 mar 11 12:31 'g_Ng#jo{!RP'
-rw-r--r-- 1 yosu users          8 mar 11 12:31 'dhell.HelloAppTest: @AfterClass - runOnceAtTheEnd'
-rw-r--r-- 1 yosu users          8 mar 11 12:31 '&W+[(?chr|-'
-rw-r--r-- 1 yosu users          8 mar 11 12:31  f8o2.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:31  fo2o2.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:31  fo2.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:31  foo2.t9races
-rw-r--r-- 1 yosu users          8 mar 11 12:31  foo2traces
-rw-r--r-- 1 yosu users          8 mar 11 12:31 '#oo2.traces'
-rw-r--r-- 1 yosu users          8 mar 11 12:29  foMo2.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:29 'foo2.=races'
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hello_run3.t9aces
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hello_run3.trces
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hello_runC3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:24 'drmWUE([ NxcyWZka'
-rw-r--r-- 1 yosu users          8 mar 11 12:24 'hello_run3.tr aces'
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hello_run3traces
-rw-r--r-- 1 yosu users          8 mar 11 12:24 'hel)o_run3.traces'
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hell0o_run3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:24  zello_run3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hello_Dun3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hel#lo_run3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:24  hell_run3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:24 '|xG[H=QPA:*Saa{)Q'
-rw-r--r-- 1 yosu users          8 mar 11 12:23 'o[;[w&^[qeq[===)J'
-rw-r--r-- 1 yosu users          8 mar 11 12:23  h{llo_run3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:23  hUello_run3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:22 '%j!9gwX1[[en#R7RX'
-rw-r--r-- 1 yosu users          8 mar 11 12:22  helloI_run3.traces
-rw-r--r-- 1 yosu users          8 mar 11 12:22  hello_run3.trRces
-rw-r--r-- 1 yosu users         92 mar 11 12:19  bar.txt
-rw-r--r-- 1 yosu users       1673 mar 11 12:18  Jenkinsfile
```

#### Steps to reproduce
Tested on DHell project with default dspot.properties and DSpot execution:
`-Xms2048m -Xmx4096m -jar $dspotJar --path-to-properties $dspotPropertiesFile -i 4 --test all -a MethodAdd:AllLiteralAmplifiers:MethodGeneratorAmplifier`

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

I guess it is the dhell project that generates this kind of file. 

If you apply some input amplifiers, you obtain what you listed: `hel#lo_run3.traces` (replace a char by another one), `'App should return some info'` (reuse an existing string in test), `&W+[(?chr|-` (random string). This name are cleary coming from the amplification.

However, I don't know what to do. IMHO, the test suite that we want to amplify should be itself "clean" and not generating files at the root of the project, and here, this is not the case. The problem comes from the test suite and not from DSpot.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
I will check the updates in Dhell tests I got this morning after pulling and I will disable those that are causing the problem. Of course, is this is the case, then, there is nothing to do in DSpot and I will close this issue. Thanks for your feedback.
