### ISSUE TITLE
Multiple amplifiers in DSpot Maven plugin

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#738]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: DSpot Maven plugin
- **Execution Environment**: Linux
- **Reporter**: [Jeús Gorroñogoitia, jesus.gorronogoitia@atos.net] &  [Ricardo Tejada, ricardo.tejada@atos.net] 

#### Description

[ERROR] Failed to execute goal eu.stamp-project:dspot-maven:2.0.0:amplify-unit-tests (default-cli) on project hello_app: Execution default-cli of goal eu.stamp-project:dspot-maven:2.0.0:amplify-unit-tests failed: java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant eu.stamp_project.utils.options.AmplifierEnum.MethodAdd:MethodGeneratorAmplifier:AllLiteralAmplifiers ->

##### Properties file

Desfault

##### Command Line / Options

mvn eu.stamp-project:dspot-maven:LATEST:amplify-unit-tests -Dpath-to-properties=/home/yosu/Projects/STAMP/Git/dhell/dspot_properties/dspot80_03_19_11_23_30.properties -Dmax-test-amplified=200 -Damplifiers=MethodAdd:MethodGeneratorAmplifier:AllLiteralAmplifiers -Diteration=1

**Comment by jesus-gorronogoitia** [comment]
I confirm this issue. It is preventing us from adopting DSpot in out Jenkins CI. Only one amplifier can be used at a time. I assume solving it is straightforward, as it seems it is not managing correctly the list of amplifies separated by colon, which are passed as a whole to the Enum for resolution.

**Comment by danglotb** [comment]
Hello, thank you for reporting this. I'm gonna investigate the issue.

**Comment by danglotb** [comment]
I am afraid that this is a misuse. In fact, when provided a list as an argument to a maven goal on the command line, we must separate elements with a colon (as you said) `,` and we do not have to use the system path separator.

However, I'll provide a new feature that split the argument if it contains only one element and the system path separator and initializer correctly the list of amplifiers to allows the usage of `:` as a separator.

**Comment by danglotb** [comment]
I just merged #739. You should no longer encounter this issue.
