### ISSUE TITLE
Question: Example provided in readme fails

### ISSUE THREAD

**Issue by borisbaldassari** [STAMP-project/dspot#740]
#### Characteristics
- **Issue Type**: bug/question
- **Reproducibility**: always
- **Severity**: minor*
- **Tool/Service/Component**: [name, version]
- **Execution Environment**: Linux (Debian 9), 64 bits, JDK Oracle 1.8.0_201
- **Reporter**: see github login

#### Description

When I try to run the example provided in the main readme file, it fails with the following message:
```shell
boris@kadath:dspot$ java -jar target/dspot-2.0.1-SNAPSHOT.jar --example
aucun attribut manifest principal dans target/dspot-2.0.1-SNAPSHOT.jar
```

I'm probably doing something wrong, can you please help? 

#### Steps to reproduce

Clone/Unzip repository, build project, run example. 
Can reproduce 100% on my machine.

##### Properties file

The one provided in the repo (not modified)

##### Command Line / Options

```shell
boris@kadath:dspot$ java -jar target/dspot-2.0.1-SNAPSHOT.jar --example
aucun attribut manifest principal dans target/dspot-2.0.1-SNAPSHOT.jar
```

**Comment by danglotb** [comment]
Hello @borisbaldassari 

Thank you for reporting this issue.

It seems that you are using the jar of dspot, _i.e._ `dspot-2.0.1-SNAPSHOT`, and not the complete jar with dependencies, _i.e._ `dspot-2.0.1-SNAPSHOT-jar-with-dependencies`.

The correct command line would be :

```sh
java -jar target/dspot-2.0.1-SNAPSHOT-jar-with-dependencies.jar --example
```

please tell me if you are able to run the provided example with this jar.

**Comment by borisbaldassari** [comment]
Fair enough, it works when using the correct command line. Dont know how i overlooked that.. 
Thank you Benjamin!
