### ISSUE TITLE
DSpot 2.1.0 release

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#758]
Announcing the new release of DSpot.

A lot of change occurs recently, and it is time to release time.

Waiting for #726, ~~#736~~, ~~#750~~, ~~#751~~, #753, ~~#755~~ and #757 to be merged/closed/resolved.

The current change log is:

# New features

* Split now the value of parameter amplifiers and init well the list.
* Recover from errors when first exec of tests.
* Forbid the class java.net.URL in the observations.
* Can now specify a list of package to forbid in the observations.
* Allow snapshot versions for PIT and Descartes.
* Generate after class.
* Pitest minimizer.
* Dspot prettifier process.
* Code2vec parser.
* Using maven to execute tests.
* Prettifier code2vec executor.

# Bug Fixes

* Get filter automatic builder helper Fix #744.
* Can generate a value for type stack over flow.
* Is test junit3.
* Assertion remover on returned values.
* The output path is now well configured.
* Fix gradle properties and skip compile test.
* Rm try with resource.
* Typo in the constant of isEqualsTo and isNotEqualsTo.
* Use now the complete classpath to compile the newly amplified test class.
* Fix is collection and is map in observations.
* Fix code2vec parser.
* GoogleTruth is now a Decorator and uses another implementation.
* Compilation errors due to amplification during the process.
* Use the property outputDirectory.
* Negate the conditional to take all but total instead of only total.
* Cloner avoid npe in init.
* Remove generic actual type arguments.
* Fix remove assertion npe.

# Documentation

* Improve diff test selection documentation FIX #768.
* Rename filter property Fix #747.
* Add example to improve coverage with Maven plugin.
* Split the README to push forward the usage.
* Patching issue#605. Fixing DSpot Maven usage example.

# Refactoring

* Report architecture fix #745.
* Remove all the old files that was not used anymore.
* Remove all files related to an experimentation.

# Performance

* Memory optimization.
* Optimization4.
* Optimization#3.
* In DSpotUtils.printAndCompileToCheck(): extract invocation type.getMethods() out of stream filter loop, since it is an invariant.

# Unknown

* Bump jacoco and spoon.
* Prettifier set exe jar.

# Authors
| Name    | Nb Commit |
|---------|-----------|
| Benjamin DANGLOT | 37 |
| Jesús Gorroñogoitia Cruz | 4 |
| Oscar Luis Vera Pérez | 1 |
| Martin Monperrus | 1 |

**Comment by nicolabertazzo** [comment]
Hi @danglotb,
When do you plan to release DSpot 2.1.0 in maven central?
I need it to define a pipeline and test dspot diff in a multi module maven project.

**Comment by danglotb** [comment]
Hello @nicolabertazzo 

I can release right now if you need. The issues that were announced to be included in the release will take some times to be developed.

I'll release in a few minutes.

**Comment by danglotb** [comment]
`dspot-2.1.0` has been released. It will available on maven central soon.

- [ ] TODO: Announce the release.
