### ISSUE TITLE
Documentation: Improve Dspot diff documentation

### ISSUE THREAD

**Issue by nicolabertazzo** [STAMP-project/dspot#768]
#### Characteristics
- **Issue Type**:  feature
- **Reproducibility**: always
- **Severity**: feature
- **Tool/Service/Component**: dispot-diff / documentation
- **Execution Environment**:
- **Reporter**: @nicolabertazzo , nicola.bertazzo@eng.it

#### Description
Hi @danglotb,

Some properties used to execute Dspot diff are not documented.

This command line properties is not documented:

- path-to-test-list-csv

This dspot.proerties properties is not documented:

- configPath

The name of this dspot.properties is not clear:

- folderPath

I suggest to add a description of this properties also in dspot-diff-test-selection (because it's mandatory when you want to use dispot-diff)

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Hello @nicolabertazzo 

> configPath

Is no longer needed nor available.

> I suggest to add a description of this properties also in dspot-diff-test-selection (because it's mandatory when you want to use dispot-diff)

It is not. The **dspot-diff-test-selection** does not need any properties file. It is if you want to run sequencially **dspot** and **dspot-diff-test-selection**.

>This dspot.proerties properties is not documented:

Thank you, I added specific options of the maven plugin.

Please review #769

**Comment by nicolabertazzo** [comment]
Tnx @danglotb ,

I found the [maven property ](https://github.com/STAMP-project/dspot/blob/cff8374103a540498dfc8799d15e97dfcf932e2f/dspot-maven/src/main/java/eu/stamp_project/DSpotMojo.java#L228). 

I'll test it and I'll update.

**Comment by nicolabertazzo** [comment]
I tested maven properties with the SNAPSHOT version and it works.
I'll wait the stable version to integrate it on CI/CD in Jenkins.
