### ISSUE TITLE
prepare demo mixing table + dspot

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#8]
Motivation: most software engineering demos are boring because there are just log files and source code to look at. adding a physical device in the demo makes much more fun.

What: preparing a demo when what drives the test amplification process using a [mixing table](https://www.amazon.fr/AKAI-Pro-MIDIMIX-Contr%C3%B4leur-Ultra-Performant/dp/B00XJE3W7C). Each knob of the table would be bound to an amplification configuration parameter. The live coverage or mutation score would be impacted in real time and visualized fancily on screen. 

Output: A cool DSpot demo that uses  mixing table

**Comment by monperrus** [comment]
good progress in Stockholm and kudos to @barais and @oscarlvp for the first version.

Can we move the code of the first version to the STAMP-project organization?

**Comment by barais** [comment]
It is already the case
https://github.com/STAMP-project/dspot-visu

**Comment by monperrus** [comment]
excellent! then we can close the issue.

thanks!
