### ISSUE TITLE
DSpot maven plugin generates a file called NUL (!) in current directory

### ISSUE THREAD

**Issue by gibello** [STAMP-project/dspot#800]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: DSpot maven 2.1.0 release
- **Execution Environment**: Ubuntu linux 18.04
- **Reporter**: Pierre-Yves Gibello, pyg@ow2.org

#### Description

When running DSpot maven plugin on the DSpot example project, a file called "NUL" is generated (with some logs inside).

#### Steps to reproduce

From the root dir of DSpot,
cd dspot/src/test/resources/test-projects

Then,
mvn eu.stamp-project:dspot-maven:amplify-unit-tests

Everything runs fine, but at the end, a log file called "NUL" appears.

**Comment by danglotb** [comment]
The problem comes from the `test-runner`. 

I opened  stamp-project/testrunner#71 to fix it, the file will be generating in the temporary folder (_e.g._ `/tmp` on Linux) instead of at the root of the project.
