### ISSUE TITLE
Command-line options error with NO info (and few doc...)

### ISSUE THREAD

**Issue by gibello** [STAMP-project/dspot#819]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: DSpot maven plugin 2.1.1-SNAPSHOT
- **Execution Environment**: Ubuntu 18.04
- **Reporter**: Pierre-Yves Gibello, pyg@ow2.org

#### Description

When an error is detected in command-line options, the following error is displayed:

```
[ERROR] Failed to execute goal eu.stamp-project:dspot-maven:2.1.1-SNAPSHOT:amplify-unit-tests (default-cli) on project joram-mom: Execution default-cli of goal eu.stamp-project:dspot-maven:2.1.1-SNAPSHOT:amplify-unit-tests failed: eu.stamp_project.utils.options.check.InputErrorException: Error in the provided input. Please check your properties file and your command-line options. -> [Help 1]
```

Nothing about the wrong or missing option (which one is it ? how to guess ?). Stack traces don't provide more info.

Documentation is missing as well: maven plugin options seem to have different names than command-line options (sometimes, at least ?), but the user has to guess...

**Comment by danglotb** [comment]
Could please provide me the command line options you are using and your properties file?

Be careful, with the last commit, some command line options changed to be more consistent (using all the same pattern). This is the risk when you use a SNAPSHOT.

> maven plugin options seem to have different names

This is not true since the maven plugin options are generated from the command line options (unless some extra maven options that are manually added.)

**Comment by gibello** [comment]
Something like that (and concerning the properties, I tried to specify a "project", and tried without properties as well: same issue).
Note that removing elements in the configuration part does not seem to change much...

Anyway, what is missing is details of the error (which parameter is wrong or missing or invalid...), not just a generic message about an unspecified wrong param...

```
      <plugin>
           <groupId>eu.stamp-project</groupId>
           <artifactId>dspot-maven</artifactId>
           <version>2.1.1-SNAPSHOT</version>
           <configuration>
              <targetModule>core</targetModule>
              <src>src/main/java</src>
              <testSrc>src/test/java</testSrc>
              <testCriterion>JacocoCoverageSelector</testCriterion>
              <output-path>target/dspot/output</output-path>
              <verbose>true</verbose>
              <generate-new-test-class>true</generate-new-test-class>
           </configuration>
        </plugin>
```
I finally succeeded launching DSpot without any config in the pom, like this:

```
mvn eu.stamp-project:dspot-maven:2.1.1-SNAPSHOT:amplify-unit-tests -Dtest-criterion=JacocoCoverageSelector -Dgenerate-new-test-class=true -Diteration=1
```

Note: Concerning the change in param names, it would be fine if backward compatibility was ensured (at least between RELEASEs, not necessarily btw snapshots). An old param name should result in a "deprecated" or warning message, not an error... Otherwise, the "risk" of using snapshots becomes a "risk" of using new releases ;)
