### ISSUE TITLE
[Refactor] Replace all properties by a command-line option

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#826]
Hello all,

I'm opening this thread to discuss the way DSpot is configured.

For now, DSpot uses both command-line options and properties defined in a file.

Some of them are overlapping (_e.g._ if you specify `--output-path (-o)` and the property `outputDirectory`, the command-line option is taken).

In one hand, it avoids very large command-line options. On the other hand, it may confuse the user.

There are also some problems with `dspot-maven`.

The question is: 
- should keep at it is?
- should we merge all properties into the command-line options?
- should we refactor and select specific inputs to be used as properties of command-line options?

Since this issue is all about users, I'm kindly asking our partners to take part in this discussion.

WDYT @gibello @vmassol @jesus-gorronogoitia @pedrovelho?

On my side, I'm also a user but my point of view is biased since I know deeply DSpot.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb, thanks for this debate. IMHO I would vote for configure DSpot using a single approach, either using a properties file or command line options (but not both). Now I am using Jenkins CI for running parameterized jobs of DSpot, I  would say that command line options are more suitable for Jenkins, but I have not an strong position whether to use a properties file or a command line options.

**Comment by gibello** [comment]
Hi @danglotb ,
Like Jesus, I prefer command-line options (but if they supersede all config file properties, no problem).
And, as I generally use the maven plugin, I consider the plugin configuration in the pom as a kind of properties file, sufficient for my needs.

**Comment by danglotb** [comment]
Hello,

Thank you for your answers.

It was my intuition: one way to configure DSpot is enough, even if this one grows a bit.

IHMO, using only properties file is not reasonable since it is difficult to customize run through scripts.

I would also vote to transform all the properties into command-line options.

> I would say that command-line options are more suitable for Jenkins

I would say that command-line options are more suitable for the global usage of DSpot.

I think that no human would use DSpot by hands (unless to learn how to use it) but everybody would end up either with a maven configuration (such as @gibello) or using scripts (I assume that Jenkins CI configuration can be assimilated to a script).

Thank you.

I'm gonna think on the next step.

**Comment by nicolabertazzo** [comment]
Hi @danglotb ,
Like @jesus-gorronogoitia and @gibello I prefer command-line options and all configuration maven pom.xml file.

**Comment by danglotb** [comment]
Hi @nicolabertazzo 

I was thinking that I forgot you, sorry.

Seems like the majority would prefer to avoid this properties file.

I'm gonna turn this issue as a requested refactor and work on it when I have the time.

Thank you all.

If you have more idea/suggestions on the way we should configure DSpot, do not hesitate to point them now and on this thread.
