### ISSUE TITLE
Refactor: assertgenerator

### ISSUE THREAD

**Issue by andrewbwogi** [STAMP-project/dspot#828]
#### Characteristics
- **Issue Type**: [refactor]
- **Reporter**: [Andrew Bwogi, bwogi.andrew@gmail.com]

#### Description

The classes in the folder [assertiongenerator](https://github.com/STAMP-project/dspot/tree/master/dspot/src/main/java/eu/stamp_project/dspot/assertgenerator) could be renamed because now they have too similar names. Methods in classes could be divided into several smaller methods. Perhaps a file hierarchy between classes could be created to better indicate dependency relations. I can take care of this issue.

**Comment by danglotb** [comment]
Thank @andrewbwogi for proposing this.

Do not hesitate if you need help!

**Comment by andrewbwogi** [comment]
Closed with #859.
