### ISSUE TITLE
Can't run dspot-maven version 2.1.1 on Maven Multimodule project 

### ISSUE THREAD

**Issue by nicolabertazzo** [STAMP-project/dspot#829]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major,crash
- **Tool/Service/Component**: dspot-maven, >2.1.0
- **Execution Environment**:  linux, ubuntu
- **Reporter**: @nicolabertazzo 

#### Description
My goal is to execute dspot in all the module of a Multimodule Maven project.
I configure the parent pom.xml and execute dspot on it.
If i use dspot 2.0.0 or 2.1.0 it works.
If i use dspot 2.1.1 it fails with these error:

`[ERROR] Failed to execute goal eu.stamp-project:dspot-maven:2.1.1:amplify-unit-tests (default-cli) on project parent: Execution default-cli of goal eu.stamp-project:dspot-maven:2.1.2-SNAPSHOT:amplify-unit-tests failed: eu.stamp_project.utils.options.check.InputErrorException: Error in the provided input. Please check your properties file and your command-line options. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
`
#### Steps to reproduce

- Clone this repo: https://github.com/STAMP-project/joram.git
- Checkout branch issue829
- Run these commands:

`cd joram
mvn clean eu.stamp-project:dspot-maven:amplify-unit-tests
`

if you change dspot version to 2.0.0 or 2.1.0 it works (joram/pom.xml row 204).

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
It is because DSpot has been developed in a way that it targets one module at the time.

I'm gonna add a command-line option that specifies that you want to run DSpot on all modules.

But I'm kind of confused. I'm not sure it is the best way to use DSpot.

I did run it on all the modules of Joram, but you have a lot of errors that come up because of modules without any test.

There is some issue with the way that DSpot checks the input.

I'm gonna work on that, at the same time than #826

**Comment by danglotb** [comment]
I just opened #831 that add new command line option for the maven plugin:

`-Drun-on-all-modules`: DSpot will be executed on all modules that he found.

However, some errors will appear.

The other way to do it, he to specify a properties file and the property `targetModule`.

**Comment by nicolabertazzo** [comment]
Ok I'll try it.

Nicola

**Comment by danglotb** [comment]
Hi @nicolabertazzo 

Any news about this issue?

**Comment by nicolabertazzo** [comment]
I execute some tests on joram project and it looks like they are ok.
