### ISSUE TITLE
The embedded tests are not passing

### ISSUE THREAD

**Issue by paraita** [STAMP-project/dspot#83]
running `mvn test`seem to fail on my machine.
`mvn compile`works fine though.
Here is attached the log of the `mvn test`.
I'm running those commands from the master branch.

[mvn_test.txt](https://github.com/STAMP-project/dspot/files/850992/mvn_test.txt)

**Comment by danglotb** [comment]
Hello, thanks you for reporting the bug.

The decimal separator used in the expected string is not the same the generated one.

#85 will fix this.
