### ISSUE TITLE
BUG: Excluded classes not working in DSpot Maven

### ISSUE THREAD

**Issue by RicardoTej** [STAMP-project/dspot#837]
#### Characteristics
- **Issue Type**: bug/Misuse
- **Reproducibility**: always
- **Tool/Service/Component**: DSpot Maven, Latest
- **Execution Environment**: Linux
- **Reporter**: Ricardo Tejada ricardo.tejada@atos.net

#### Description

Using DSpot on dhell project, the properties file contains excludedClasses=eu.stamp_project.examples.dhell.MyStorageTest
but DSpot is amplifiying the two tests (HelloAppTest and MyStorageTest)
(HelloAppTest and MyStorageTest JSon and txt summaries are beeing produced)

##### Properties file

project=/home/ricardo/STAMP/ProyectosPrueba/dhell
testSrc=/home/ricardo/STAMP/ProyectosPrueba/dhell/src/test/java
src=/home/ricardo/STAMP/ProyectosPrueba/dhell/src/main/java
javaVersion=8
excludedClasses=eu.stamp_project.examples.dhell.MyStorageTest

##### Command Line / Options

mvn eu.stamp-project:dspot-maven:amplify-unit-tests -Dpath-to-properties=/home/ricardo/...

**Comment by RicardoTej** [comment]
Maybe it is because of PitMutantScoreSelector

**Comment by danglotb** [comment]
Hello @RicardoTej 

It was a bug. I just opened #838 to fix it. Best,
