### ISSUE TITLE
TEST: Context2NameTest#testContext2Name seems to be failing

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#876]
Hello,

I just found out that the test in dspot-prettifier `Context2NameTest#testContext2Name` seems to be failing.

In the shell script, the installation of required dependencies was after the `mvn test` goal. So the build the tests were not passing but the build was because the installation went fine.

In #875, I swapped the order and `@Ignore` the test method.

@jianguda could you have a look at this? Thank you.

**Comment by jianguda** [comment]
Hey @danglotb sorry for missing your message, I will check this later this week.

**Comment by jianguda** [comment]
Hey @danglotb 
I checked and found it is not because of `Context2NameTest`
Here is my [CI result](https://travis-ci.org/orz/dspot/builds/596953699)
