### ISSUE TITLE
Dspot fails on project javapoet

### ISSUE THREAD

**Issue by borisbaldassari** [STAMP-project/dspot#881]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Execution Environment**: Linux 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux

#### Description

Executing dspot-maven on javapoet fails. The project compiles ok (mvn package) but executing `mvn eu.stamp-project:dspot-maven:amplify-unit-tests` fails (see logs).

#### Steps to reproduce

Run dspot on javapoet:
```
$ mvn eu.stamp-project:dspot-maven:amplify-unit-tests 
```

##### Properties file

No properties file is required when running the maven utility. However I tried with a dspot.properties added file (still using maven) and result is the same (see logs).

##### Command Line / Options

[javapoet_mvn_dspot.log](https://github.com/STAMP-project/dspot/files/3646993/javapoet_mvn_dspot.log)
[javapoet_mvn_dspot_properties.log](https://github.com/STAMP-project/dspot/files/3646994/javapoet_mvn_dspot_properties.log)
[javapoet_mvn_package.log](https://github.com/STAMP-project/dspot/files/3646995/javapoet_mvn_package.log)

**Comment by danglotb** [comment]
Hello @borisbaldassari 

Thank for reporting this. On my side, it is able to perform the amplification.

On your traces, we can see that the problem occurs when DSpot computes the baseline of the mutation score: 

```txt
[INFO] run maven: /home/boris/Applis/apache-maven-3.6.0/bin/mvn org.pitest:pitest-maven:mutationCoverage 
[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.


[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

The most important is `[INFO] run maven: /home/boris/Applis/apache-maven-3.6.0/bin/mvn org.pitest:pitest-maven:mutationCoverage ` meaning that DSpot is running PIT using the `pit-maven-plugin`.

Could you enable the verbose mode by using `-Dverbose=true` on your maven command line and provide me the log? With this flag, we will see the output of the internal maven goals run by DSpot.

It can come from a generated file by DSpot. Please check if you have generated hidden `pom` files named like ` .dspot_junit5_pom.xml` or `.dspot_pom.xml`, and remove them.

Also, you could try to use the latest version of DSpot, on your traces, we can see that you are using `dspot-maven:2.0.0:amplify-unit-tests (default-cli) @ javapoet`.

**Comment by borisbaldassari** [comment]
Hello @danglotb!

> It can come from a generated file by DSpot. Please check if you have generated hidden `pom` files named like ` .dspot_junit5_pom.xml` or `.dspot_pom.xml`, and remove them.

There are indeed a couple of similar auto-generated files:
.dspot__junit5_pom.xml
.dspot_junit5_pom.xml
.dspot_pom.xml

Removed them, re-running mvn now.

> Also, you could try to use the latest version of DSpot, on your traces, we can see that you are using `dspot-maven:2.0.0:amplify-unit-tests (default-cli) @ javapoet`.

Hum. I thought that when using mvn we'd use the latest published jar of dspot, strange. I'll look into that. 

Thanks!

**Comment by borisbaldassari** [comment]
Fixed. I had to remove manually all the dspot-* jars from my .m2 directory, so mvn had to download it again and I'm now using dspot 2.2.0 instead of 2.0.0. Don't know why it didn't pick the latest version automatically though.

Now it builds successfully. Only one test class is generated with the default set of options, so i'll try different options. 

Thanks again for the support! :-)
