### ISSUE TITLE
Wrapper object set to null causes crash

### ISSUE THREAD

**Issue by andrewbwogi** [STAMP-project/dspot#900]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: DSpot 2.2.0
- **Execution Environment**: Arch Linux 2019.01.01
- **Reporter**: Andrew Bwogi, bwogi.andrew@gmail.com

#### Description
DSpot crashes when it amplifies wrapper objects set to null. 

#### Steps to reproduce
Set for instance `Boolean b = null;` in the test method to be amplified and run DSpot as usual. 

##### Properties file

```java
project=.
src=src/main/java/
testSrc=src/test/java/
```

##### Command Line / Options

```shell
java -jar dspot-2.2.0-jar-with-dependencies.jar -p myPropertiesFile.properties
```

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by andrewbwogi** [comment]
I can fix this.

**Comment by danglotb** [comment]
Awesome @andrewbwogi Thank you very much.
