### ISSUE TITLE
bug: the devil may hide inside the DSpot repo

### ISSUE THREAD

**Issue by monperrus** [STAMP-project/dspot#902]
#### Characteristics
- **Issue Type**: paranormal
- **Reproducibility**: always
- **Severity**: blocker
- **Tool/Service/Component**: dspot repo
- **Execution Environment**: world
- **Reporter**: Martin Monperrus

#### Description

The devil is in DSpot, we have 666 commits.

#### Steps to reproduce

Open https://github.com/STAMP-project/dspot/, look at the number of commit.

**Urgent action**: do one commit to push the devil back

**Comment by danzone** [comment]
Sorry @danglotb, I had to respond to @monperrus call immediately

**Comment by monperrus** [comment]
FYI
GitHub satanically messing with Markdown - changes 666 to DCLXVI
https://stackoverflow.com/questions/44619165/github-satanically-messing-with-markdown-changes-666-to-dclxvi?rq=1
