### ISSUE TITLE
Refactor DSpot to highlight the application loop

### ISSUE THREAD

**Issue by andrewbwogi** [STAMP-project/dspot#918]
#### Characteristics
- **Issue Type**: refactor
- **Reporter**: Andrew Bwogi, bwogi.andrew@gmail.com

#### Description
The DSpot module can be refactored and reorganized to highlight the application loop and its stages. For this, the distance between the Main class and the loop implementation can be decreased by putting most of the code in Main, DSpot and Amplification in a Configuration class and then merging the DSpot class with the Amplification class. 

To highlight the application loop in the folder structure as well, the contents of the folders utils, automaticbuilder and test_framework should be distributed when appropriate to the folders representing the stages of the loop. The remaining content should make up a 'common' folder containing general tools.

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by andrewbwogi** [comment]
I'm currently working on this.

**Comment by danglotb** [comment]
Hello @andrewbwogi 

Thank you for proposing this. Any update on your progress?

**Comment by andrewbwogi** [comment]
There is a PR for the first part of the issue.

**Comment by danglotb** [comment]
Can I close this one?

**Comment by andrewbwogi** [comment]
Hi @danglotb, let me try to reorganize the package structure before closing this.
