### ISSUE TITLE
support more results from pit

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#92]
Pit produces sometimes a results such as:

> QueryParser.java;org.jsoup.select.QueryParse;rorg.pitest.mutationtest.engine.gregor.mutators.ArgumentPropagationMutator;cssNthChild;303;KILLED;org.jsoup.select.CssTest.org.jsoup.select.CssTest

The PitResultParser does not support this kind of results.

**Comment by monperrus** [comment]
closed per https://github.com/danglotb/dspot/commit/36ea54cce5c5edf8c2dc8e17c5962c05e18a0c4c
