### ISSUE TITLE
Unknown Amplifiers in dspot-maven

### ISSUE THREAD

**Issue by borisbaldassari** [STAMP-project/dspot#921]
#### Characteristics
- **Issue Type**: documentation
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: Dspot-maven 3.0.0
- **Execution Environment**: Linux Debian 9.11

#### Description

When executing the new maven-dspot 3.0.0 goal with a set of known amplifiers it fails with the following message: 

```shell
MAVEN_HOME=~/Applis/apache-maven-3.6.0/ mvn eu.stamp-project:dspot-maven:amplify-unit-tests -Doutput-path=../output/dspot -Diteration=1 -Damplifiers=FastLiteralAmplifier,MethodAdd,MethodRemove,MethodGeneratorAmplifier

picocli.CommandLine$ParameterException: Invalid value for option '--amplifiers' (<amplifiers>): expected one of [MethodDuplicationAmplifier, MethodRemove, FastLiteralAmplifier, MethodAdderOnExistingObjectsAmplifier, ReturnValueAmplifier, StringLiteralAmplifier, NumberLiteralAmplifier, BooleanLiteralAmplifier, CharLiteralAmplifier, AllLiteralAmplifiers, NullifierAmplifier, ArrayAmplifier, None] (case-sensitive) but was 'MethodAdd'
```

When double-checking, it seems that `MethodAdd`, `MethodGeneratorAmplifier` are not supported anymore. Have they been replaced, or is there any documentation to help?

There is no mention of amplifiers being deprecated, by the way.

##### Command Line / Options

```shell
MAVEN_HOME=~/Applis/apache-maven-3.6.0/ mvn eu.stamp-project:dspot-maven:amplify-unit-tests -Doutput-path=../output/dspot -Diteration=1 -Damplifiers=FastLiteralAmplifier,MethodAdd,MethodRemove,MethodGeneratorAmplifier
```

**Comment by danglotb** [comment]
Hello @borisbaldassari 

`MethodAdd` has been replaced by `MethodDuplicationAmplifier` and `MethodGeneratorAmplifier` has been replaced by `MethodAdderOnExistingObjectsAmplifier`.

New names have been introduced in #846. By the time, old and new names were supported, and a warning message was displayed in case you used an old name.

Thank you.

**Comment by borisbaldassari** [comment]
Hi @danglotb ,
Thanks for the clarification, I've overlooked that.. closing the bug. Thanks again for your support!
