### ISSUE TITLE
add support for gradle projects

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#96]
Motivations: For now, DSpot can only be run on maven projects.
 
What: The task aims at adding a support for projects that use gradle.

Expected changes: It consists of adding an interface above the existing usage of all call to maven and implement same usage with gradle. It will allow the user to specify in the properties file or automatically detected (the pom.xml exists) which tool his project is using.

**Comment by danglotb** [comment]
This issue will be easier with the merge of #133, it reduce it to the implementation of getting the classpath and running pit with gradle

**Comment by danzone** [comment]
hi @danglotb, just started to look at DSpot code. Following method calls, I've come to the first reference of a maven call through DSpotUtils.compileOriginalProject() -> MavenBuilder. Adding Gradle support needs it should be refactored, and a GradleBuilder should be implemented in sosiefier to abstract from system builder. But I'm completely new to DSpot code, what are your advices to proceed?

**Comment by danglotb** [comment]
Hello @danzone,

Actually I did a Pull request that refactor all the code #133. 

I removed the dependencies to sosiefier for the MavenBuilder. This pull request propose an interface of AutomaticBuilder. Only maven builder is implemented.

I'll merge it just after this comment. I propose you to update the base code afterwards and then you will need to:

1. implement a GradleBuilder that extends the interface.
2. add a property into the properties file or an option (see JSAPOptions) to specify which automatic builder DSpot must use.
3. change all hard coded usage of MavenBuilder by using the previously configurable options. (I put a comment //TODO where this Builder is used)

If you have any trouble, do not hesitate!

Thank you.

**Comment by danzone** [comment]
Hi @danglotb, yesterday I completed the support to config/options, to let user specify the automatic builder, and replaced direct calls to MavenAutomaticBuilder with a Factory which provides the selected builder. I run all the tests, everything worked fine. And in the evening I realized I can't make push, pull requests to submit my changes. In a first moment I guessed it was an issue due to our corporate proxy, but today, at home, with no proxy around, had the same issue, and tried to make a pull request directly on Github, with the same problem. Could you please check my permissions? Thanks.

**Comment by danglotb** [comment]
Hello @danzone,

I would like that you propose your changes through a pull request across fork.

You have to first fork dspot on your own account. Then push your changes into a new branch on your fork. Finally, on the github page of dspot, you can open a pull request across the main repository and your fork.

This will trigger travis for the ci, and I will be able to review your changes and merge it.

Thank you!

**Comment by danzone** [comment]
Hi @danglotb , could be please remove the label "task available"? I don't have permissions to remove it. Thanks.
