### ISSUE TITLE
flaky test: one test fails during build on some machines: testBuildNewAssert / testPitEvosuiteMode

### ISSUE THREAD

**Issue by danglotb** [STAMP-project/dspot#98]
- MethodsAssertGeneratorTest#testBuildNewAssert 
- PitDescartesTest#testPitDescartesMode

**Comment by danglotb** [comment]
Hello, @danzone @nicolabertazzo

 Would you mind to give the list of the flaky tests?

Cheers.

**Comment by nicolabertazzo** [comment]
I attached the output of mvn clean package command executed on dspot project.
[mvn_clean_package.txt](https://github.com/STAMP-project/dspot/files/1299349/mvn_clean_package.txt)
